
import type { Product, Category, User, Review, Order } from './types';
import { PlaceHolderImages } from './placeholder-images';

const categories: Category[] = [
    { id: 'fresh-produce', name: 'Fresh Produce', description: 'Fresh fruits and vegetables.' },
    { id: 'dairy-bakery', name: 'Dairy & Bakery', description: 'Milk, cheese, eggs, and baked goods.' },
    { id: 'staples-pantry', name: 'Staples & Pantry', description: 'Rice, flour, dals, and other essentials.' },
    { id: 'meat-seafood', name: 'Meat & Seafood', description: 'Fresh meat and seafood items.' },
    { id: 'prepared-foods', name: 'Prepared Foods', description: 'Ready-to-eat meals.' },
    { id: 'snacks', name: 'Snacks', description: 'Chips, sweets, and other snacks.' },
    { id: 'beverages', name: 'Beverages', description: 'Drinks and beverages.' },
];

const products: Product[] = [
    // Fresh Produce
    {
        id: 'prod-potato',
        name: 'Potato (Aloo)',
        description: 'Versatile and essential for many dishes.',
        price: 30,
        stock: 100,
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-potato')!.imageUrl,
        imageHint: 'fresh potatoes',
        sellerId: 'seller-1',
        subCategory: 'Daily Vegetables',
        variants: [
            { id: 'prod-potato-500g', weight: '500g', price: 15, stock: 50 },
            { id: 'prod-potato-1kg', weight: '1kg', price: 30, stock: 30 },
            { id: 'prod-potato-5kg', weight: '5kg', price: 140, stock: 20 },
        ],
    },
    {
        id: 'prod-onion',
        name: 'Onion (Vengayam)',
        description: 'A staple in every Indian kitchen.',
        price: 40,
        stock: 80,
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-onion')!.imageUrl,
        imageHint: 'fresh onions',
        sellerId: 'seller-1',
        subCategory: 'Daily Vegetables',
         variants: [
            { id: 'prod-onion-500g', weight: '500g', price: 20, stock: 40 },
            { id: 'prod-onion-1kg', weight: '1kg', price: 40, stock: 30 },
            { id: 'prod-onion-5kg', weight: '5kg', price: 190, stock: 10 },
        ],
    },
    {
        id: 'prod-tomato',
        name: 'Tomato (Thakkali)',
        description: 'Ripe and juicy tomatoes.',
        price: 25,
        stock: 120,
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-tomato')!.imageUrl,
        imageHint: 'ripe tomatoes',
        sellerId: 'seller-1',
        subCategory: 'Daily Vegetables',
        variants: [
            { id: 'prod-tomato-500g', weight: '500g', price: 13, stock: 60 },
            { id: 'prod-tomato-1kg', weight: '1kg', price: 25, stock: 60 },
        ],
    },
    {
        id: 'prod-spinach',
        name: 'Spinach (Palak)',
        description: 'Freshly picked leafy greens.',
        price: 20,
        stock: 50,
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-spinach')!.imageUrl,
        imageHint: 'spinach leaves',
        sellerId: 'seller-1',
        subCategory: 'Leafy Greens',
    },
    {
        id: 'prod-coriander',
        name: 'Coriander (Kothamalli)',
        description: 'Aromatic and fresh coriander bunches.',
        price: 15,
        stock: 70,
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-coriander')!.imageUrl,
        imageHint: 'coriander bunch',
        sellerId: 'seller-1',
        subCategory: 'Leafy Greens',
    },
    {
        id: 'prod-mint',
        name: 'Mint (Pudina)',
        description: 'Refreshing mint leaves.',
        price: 10,
        stock: 80,
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-mint')!.imageUrl,
        imageHint: 'mint leaves',
        sellerId: 'seller-1',
        subCategory: 'Leafy Greens',
    },
    {
        id: 'prod-curry-leaves',
        name: 'Curry Leaves (Karuveppilai)',
        description: 'Essential for tempering South Indian dishes.',
        price: 8,
        stock: 100,
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-curry-leaves')!.imageUrl,
        imageHint: 'curry leaves',
        sellerId: 'seller-1',
        subCategory: 'Leafy Greens',
    },
     {
        id: 'prod-mango',
        name: 'Mango',
        description: 'Sweet and juicy seasonal mangoes.',
        price: 120,
        stock: 40,
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-mangoes')!.imageUrl,
        imageHint: 'ripe mangoes',
        sellerId: 'seller-1',
        subCategory: 'Seasonal Fruits',
    },
    {
        id: 'prod-watermelon',
        name: 'Watermelon',
        description: 'Refreshing and hydrating watermelon.',
        price: 80,
        stock: 30,
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-watermelon')!.imageUrl,
        imageHint: 'watermelon slice',
        sellerId: 'seller-1',
        subCategory: 'Seasonal Fruits',
    },
    {
        id: 'prod-grapes',
        name: 'Grapes',
        description: 'Sweet and crisp green grapes.',
        price: 90,
        stock: 60,
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-grapes')!.imageUrl,
        imageHint: 'green grapes',
        sellerId: 'seller-1',
        subCategory: 'Seasonal Fruits',
    },
    {
        id: 'prod-oranges',
        name: 'Oranges',
        description: 'Juicy and vitamin C-rich oranges.',
        price: 100,
        stock: 50,
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-oranges')!.imageUrl,
        imageHint: 'fresh oranges',
        sellerId: 'seller-1',
        subCategory: 'Seasonal Fruits',
    },
    {
        id: 'prod-apple',
        name: 'Apple',
        description: 'Crisp and delicious red apples.',
        price: 150,
        stock: 80,
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-apple')!.imageUrl,
        imageHint: 'red apples',
        sellerId: 'seller-1',
        subCategory: 'Seasonal Fruits',
    },
    {
        id: 'prod-banana',
        name: 'Banana',
        description: 'A bunch of ripe Yelakki bananas.',
        price: 40,
        stock: 100,
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-banana')!.imageUrl,
        imageHint: 'ripe bananas',
        sellerId: 'seller-1',
        subCategory: 'Seasonal Fruits',
    },
    {
        id: 'prod-broccoli',
        name: 'Broccoli',
        description: 'Fresh green broccoli florets.',
        price: 60,
        stock: 40,
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-broccoli')!.imageUrl,
        imageHint: 'fresh broccoli',
        sellerId: 'seller-1',
        subCategory: 'Exotic & Salad Veggies',
    },
    {
        id: 'prod-bell-peppers',
        name: 'Bell Peppers (Capsicum)',
        description: 'A mix of colorful bell peppers.',
        price: 70,
        stock: 50,
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-bell-peppers')!.imageUrl,
        imageHint: 'bell peppers',
        sellerId: 'seller-1',
        subCategory: 'Exotic & Salad Veggies',
    },
    {
        id: 'prod-zucchini',
        name: 'Zucchini',
        description: 'Tender and fresh zucchini.',
        price: 50,
        stock: 30,
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-zucchini')!.imageUrl,
        imageHint: 'fresh zucchini',
        sellerId: 'seller-1',
        subCategory: 'Exotic & Salad Veggies',
    },
    {
        id: 'prod-lettuce',
        name: 'Lettuce',
        description: 'Crisp and fresh lettuce head.',
        price: 45,
        stock: 40,
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-lettuce')!.imageUrl,
        imageHint: 'lettuce head',
        sellerId: 'seller-1',
        subCategory: 'Exotic & Salad Veggies',
    },
    {
        id: 'prod-avocado',
        name: 'Avocado',
        description: 'Creamy and ripe avocados.',
        price: 120,
        stock: 25,
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-avocado')!.imageUrl,
        imageHint: 'ripe avocado',
        sellerId: 'seller-1',
        subCategory: 'Exotic & Salad Veggies',
    },
    {
        id: 'prod-peeled-garlic',
        name: 'Peeled Garlic',
        description: 'Conveniently peeled garlic cloves.',
        price: 50,
        stock: 60,
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-peeled-garlic')!.imageUrl,
        imageHint: 'peeled garlic',
        sellerId: 'seller-1',
        subCategory: 'Cut & Sprouted',
    },
    {
        id: 'prod-sambhar-mix',
        name: 'Chopped Sambhar Mix',
        description: 'A mix of vegetables for sambhar.',
        price: 40,
        stock: 40,
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-sambhar-mix')!.imageUrl,
        imageHint: 'chopped vegetables',
        sellerId: 'seller-1',
        subCategory: 'Cut & Sprouted',
    },
    {
        id: 'prod-sprouted-moong',
        name: 'Sprouted Moong Dal',
        description: 'Healthy and ready-to-use sprouted moong.',
        price: 35,
        stock: 50,
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-sprouted-moong')!.imageUrl,
        imageHint: 'sprouted moong',
        sellerId: 'seller-1',
        subCategory: 'Cut & Sprouted',
    },
    {
        id: 'prod-grated-coconut',
        name: 'Grated Coconut',
        description: 'Freshly grated coconut for your recipes.',
        price: 30,
        stock: 70,
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-grated-coconut')!.imageUrl,
        imageHint: 'grated coconut',
        sellerId: 'seller-1',
        subCategory: 'Cut & Sprouted',
    },
    {
        id: 'prod-veggie-combo',
        name: 'Onion-Potato-Tomato Combo',
        description: 'A convenient combo of kitchen staples.',
        price: 85,
        stock: 30,
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-veggie-combo')!.imageUrl,
        imageHint: 'vegetable combo',
        sellerId: 'seller-1',
        subCategory: 'Combos',
    },

    // Dairy & Bakery
    {
        id: 'prod-milk-pouch',
        name: 'Aavin Toned Milk',
        description: 'Fresh toned milk from Aavin.',
        price: 22,
        stock: 150,
        categoryId: 'dairy-bakery',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-milk-pouch')!.imageUrl,
        imageHint: 'milk pouch',
        sellerId: 'seller-1',
        subCategory: 'Milk & Fresh Products',
        brand: 'Aavin',
    },
    {
        id: 'prod-milk-pouch-full',
        name: 'Heritage Full Cream Milk',
        description: 'Rich and creamy full cream milk.',
        price: 32,
        stock: 100,
        categoryId: 'dairy-bakery',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-milk-pouch-full')!.imageUrl,
        imageHint: 'milk pouch',
        sellerId: 'seller-1',
        subCategory: 'Milk & Fresh Products',
        brand: 'Heritage',
    },
    {
        id: 'prod-buttermilk',
        name: 'Spiced Buttermilk (Neer Mor)',
        description: 'Refreshing and traditional buttermilk.',
        price: 15,
        stock: 80,
        categoryId: 'dairy-bakery',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-buttermilk')!.imageUrl,
        imageHint: 'buttermilk glass',
        sellerId: 'seller-2',
        subCategory: 'Milk & Fresh Products',
    },
    {
        id: 'prod-curd',
        name: 'Fresh Curd (Thayir)',
        description: 'Thick and creamy homemade style curd.',
        price: 40,
        stock: 120,
        categoryId: 'dairy-bakery',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-curd')!.imageUrl,
        imageHint: 'curd bowl',
        sellerId: 'seller-1',
        subCategory: 'Curd & Yogurt',
    },
    {
        id: 'prod-butter',
        name: 'Amul Salted Butter',
        description: 'Classic salted butter for all your needs.',
        price: 55,
        stock: 90,
        categoryId: 'dairy-bakery',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-butter')!.imageUrl,
        imageHint: 'butter block',
        sellerId: 'seller-1',
        subCategory: 'Butter, Cheese & More',
        brand: 'Amul',
    },
    {
        id: 'prod-cheese',
        name: 'Cheese Slices',
        description: 'Perfect for sandwiches and burgers.',
        price: 120,
        stock: 70,
        categoryId: 'dairy-bakery',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-cheese')!.imageUrl,
        imageHint: 'cheese slices',
        sellerId: 'seller-2',
        subCategory: 'Butter, Cheese & More',
    },
    {
        id: 'prod-paneer',
        name: 'Fresh Paneer',
        description: 'Soft cottage cheese for curries and snacks.',
        price: 90,
        stock: 60,
        categoryId: 'dairy-bakery',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-paneer')!.imageUrl,
        imageHint: 'paneer cubes',
        sellerId: 'seller-2',
        subCategory: 'Butter, Cheese & More',
    },
    {
        id: 'prod-bread',
        name: 'Sandwich Bread',
        description: 'Soft and fresh white bread.',
        price: 45,
        stock: 100,
        categoryId: 'dairy-bakery',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-bread')!.imageUrl,
        imageHint: 'sandwich bread',
        sellerId: 'seller-2',
        subCategory: 'Fresh Bakery',
        bestBefore: '3 days',
    },
     {
        id: 'prod-chapati',
        name: 'Ready-made Chapati',
        description: 'Soft, ready-to-heat whole wheat chapatis.',
        price: 80,
        stock: 100,
        categoryId: 'dairy-bakery',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-chapati')!.imageUrl,
        imageHint: 'chapati stack',
        sellerId: 'seller-2',
        subCategory: 'Fresh Bakery',
        bestBefore: '5 days',
    },
    {
        id: 'prod-rusk',
        name: 'Tea Rusk',
        description: 'Crispy and delicious tea-time rusks.',
        price: 60,
        stock: 80,
        categoryId: 'dairy-bakery',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-rusk')!.imageUrl,
        imageHint: 'tea rusk',
        sellerId: 'seller-2',
        subCategory: 'Fresh Bakery',
        bestBefore: '30 days',
    },
     {
        id: 'prod-eggs-white',
        name: 'White Eggs',
        description: 'Farm-fresh white eggs.',
        price: 72,
        stock: 200,
        categoryId: 'dairy-bakery',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-eggs-white')!.imageUrl,
        imageHint: 'carton eggs',
        sellerId: 'seller-1',
        subCategory: 'Eggs',
        variants: [
            { id: 'prod-eggs-white-6', weight: '6 pack', price: 36, stock: 100 },
            { id: 'prod-eggs-white-12', weight: '12 pack', price: 72, stock: 100 },
        ],
    },
    {
        id: 'prod-eggs-brown',
        name: 'Brown Eggs',
        description: 'Free-range brown eggs.',
        price: 90,
        stock: 150,
        categoryId: 'dairy-bakery',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-eggs-brown')!.imageUrl,
        imageHint: 'brown eggs',
        sellerId: 'seller-1',
        subCategory: 'Eggs',
        variants: [
            { id: 'prod-eggs-brown-6', weight: '6 pack', price: 45, stock: 75 },
            { id: 'prod-eggs-brown-12', weight: '12 pack', price: 90, stock: 75 },
        ],
    },

    // Staples & Pantry
    {
        id: 'prod-ponni-rice',
        name: 'Ponni Rice',
        description: 'High-quality Ponni rice for daily meals.',
        price: 550,
        stock: 50,
        categoryId: 'staples-pantry',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-rice-bag')!.imageUrl,
        imageHint: 'rice bag',
        sellerId: 'seller-3',
        subCategory: 'Rice & Rice Products',
        variants: [
            { id: 'prod-ponni-rice-1kg', weight: '1kg', price: 60, stock: 20 },
            { id: 'prod-ponni-rice-5kg', weight: '5kg', price: 280, stock: 20 },
            { id: 'prod-ponni-rice-10kg', weight: '10kg', price: 550, stock: 10 },
        ],
    },
    {
        id: 'prod-basmati-rice',
        name: 'Basmati Rice',
        description: 'Aromatic long-grain Basmati rice for biryani.',
        price: 180,
        stock: 40,
        categoryId: 'staples-pantry',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-basmati-rice')!.imageUrl,
        imageHint: 'basmati rice',
        sellerId: 'seller-3',
        subCategory: 'Rice & Rice Products',
        variants: [
            { id: 'prod-basmati-rice-1kg', weight: '1kg', price: 180, stock: 20 },
            { id: 'prod-basmati-rice-5kg', weight: '5kg', price: 850, stock: 20 },
        ],
    },
    {
        id: 'prod-idli-rice',
        name: 'Idli Rice',
        description: 'Special parboiled rice for soft idlis.',
        price: 50,
        stock: 60,
        categoryId: 'staples-pantry',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-idli-rice')!.imageUrl,
        imageHint: 'rice grains',
        sellerId: 'seller-3',
        subCategory: 'Rice & Rice Products',
        variants: [
            { id: 'prod-idli-rice-1kg', weight: '1kg', price: 50, stock: 30 },
            { id: 'prod-idli-rice-5kg', weight: '5kg', price: 240, stock: 30 },
        ],
    },
    {
        id: 'prod-poha',
        name: 'Poha (Aval)',
        description: 'Flattened rice for quick breakfasts.',
        price: 40,
        stock: 100,
        categoryId: 'staples-pantry',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-poha')!.imageUrl,
        imageHint: 'flattened rice',
        sellerId: 'seller-3',
        subCategory: 'Rice & Rice Products',
    },
    {
        id: 'prod-atta',
        name: 'Whole Wheat Atta',
        description: 'Stone-ground whole wheat flour for rotis.',
        price: 250,
        stock: 80,
        categoryId: 'staples-pantry',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-atta')!.imageUrl,
        imageHint: 'atta flour',
        sellerId: 'seller-3',
        subCategory: 'Atta & Flours',
        variants: [
            { id: 'prod-atta-1kg', weight: '1kg', price: 55, stock: 40 },
            { id: 'prod-atta-5kg', weight: '5kg', price: 250, stock: 40 },
        ],
    },
    {
        id: 'prod-besan',
        name: 'Besan (Gram Flour)',
        description: 'Fine gram flour for snacks and batters.',
        price: 70,
        stock: 90,
        categoryId: 'staples-pantry',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-besan')!.imageUrl,
        imageHint: 'gram flour',
        sellerId: 'seller-3',
        subCategory: 'Atta & Flours',
    },
    {
        id: 'prod-rice-flour',
        name: 'Rice Flour',
        description: 'Fine rice flour for murukku and other snacks.',
        price: 45,
        stock: 70,
        categoryId: 'staples-pantry',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-rice-flour')!.imageUrl,
        imageHint: 'rice flour',
        sellerId: 'seller-3',
        subCategory: 'Atta & Flours',
    },
    {
        id: 'prod-ragi-flour',
        name: 'Ragi Flour (Finger Millet)',
        description: 'Nutritious finger millet flour.',
        price: 60,
        stock: 60,
        categoryId: 'staples-pantry',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-ragi-flour')!.imageUrl,
        imageHint: 'ragi flour',
        sellerId: 'seller-3',
        subCategory: 'Atta & Flours',
        tags: ['Low GI'],
    },
    {
        id: 'prod-toor-dal',
        name: 'Toor Dal (Sambar Paruppu)',
        description: 'Essential dal for making sambar.',
        price: 150,
        stock: 100,
        categoryId: 'staples-pantry',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-toor-dal')!.imageUrl,
        imageHint: 'toor dal',
        sellerId: 'seller-3',
        subCategory: 'Dals & Pulses',
        tags: ['High Protein'],
    },
    {
        id: 'prod-urad-dal',
        name: 'Urad Dal (Split)',
        description: 'Split urad dal for batters and tempering.',
        price: 160,
        stock: 80,
        categoryId: 'staples-pantry',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-urad-dal')!.imageUrl,
        imageHint: 'urad dal',
        sellerId: 'seller-3',
        subCategory: 'Dals & Pulses',
    },
     {
        id: 'prod-chickpeas',
        name: 'Kabuli Chana (Chickpeas)',
        description: 'High-quality chickpeas for various dishes.',
        price: 120,
        stock: 70,
        categoryId: 'staples-pantry',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-chickpeas')!.imageUrl,
        imageHint: 'chickpeas bowl',
        sellerId: 'seller-3',
        subCategory: 'Dals & Pulses',
        tags: ['High Protein'],
    },
    {
        id: 'prod-crystal-salt',
        name: 'Crystal Salt (Kallu Uppu)',
        description: 'Coarse sea salt for traditional cooking.',
        price: 20,
        stock: 200,
        categoryId: 'staples-pantry',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-crystal-salt')!.imageUrl,
        imageHint: 'crystal salt',
        sellerId: 'seller-3',
        subCategory: 'Salt, Sugar & Jaggery',
    },
    {
        id: 'prod-sugar',
        name: 'White Sugar',
        description: 'Refined white sugar.',
        price: 45,
        stock: 300,
        categoryId: 'staples-pantry',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-sugar')!.imageUrl,
        imageHint: 'sugar cubes',
        sellerId: 'seller-3',
        subCategory: 'Salt, Sugar & Jaggery',
    },
    {
        id: 'prod-jaggery',
        name: 'Jaggery (Vellam)',
        description: 'Traditional unrefined cane sugar.',
        price: 80,
        stock: 100,
        categoryId: 'staples-pantry',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-jaggery')!.imageUrl,
        imageHint: 'jaggery block',
        sellerId: 'seller-3',
        subCategory: 'Salt, Sugar & Jaggery',
    },
    {
        id: 'prod-barnyard-millet',
        name: 'Barnyard Millet (Kuthiraivali)',
        description: 'Healthy and versatile millet.',
        price: 90,
        stock: 50,
        categoryId: 'staples-pantry',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-barnyard-millet')!.imageUrl,
        imageHint: 'millet grains',
        sellerId: 'seller-3',
        subCategory: 'Healthy Millets',
        tags: ['Low GI'],
    },
    {
        id: 'prod-foxtail-millet',
        name: 'Foxtail Millet (Thinai)',
        description: 'Nutrient-rich foxtail millet.',
        price: 95,
        stock: 50,
        categoryId: 'staples-pantry',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-foxtail-millet')!.imageUrl,
        imageHint: 'foxtail millet',
        sellerId: 'seller-3',
        subCategory: 'Healthy Millets',
        tags: ['Low GI', 'High Protein'],
    },

    // Meat & Seafood
    {
        id: 'prod-chicken-curry-cut',
        name: 'Chicken Curry Cut',
        description: 'Fresh, bone-in chicken pieces perfect for curries.',
        price: 250,
        stock: 20,
        categoryId: 'meat-seafood',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-chicken-curry-cut')!.imageUrl,
        imageHint: 'chicken curry cut',
        sellerId: 'seller-1',
        subCategory: 'Chicken (Kozhi)',
        tags: ['Halaal', 'Antibiotic-free'],
    },
    {
        id: 'prod-chicken-boneless',
        name: 'Chicken Breast Boneless',
        description: 'Tender, boneless chicken breast for various dishes.',
        price: 350,
        stock: 15,
        categoryId: 'meat-seafood',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-chicken-boneless')!.imageUrl,
        imageHint: 'boneless chicken',
        sellerId: 'seller-1',
        subCategory: 'Chicken (Kozhi)',
        tags: ['Halaal'],
    },
    {
        id: 'prod-country-chicken',
        name: 'Country Chicken (Nattu Kozhi)',
        description: 'Flavorful country chicken for traditional gravies.',
        price: 450,
        stock: 9,
        categoryId: 'meat-seafood',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-country-chicken')!.imageUrl,
        imageHint: 'country chicken',
        sellerId: 'seller-1',
        subCategory: 'Chicken (Kozhi)',
    },
    {
        id: 'prod-mutton-curry-cut',
        name: 'Mutton Curry Cut',
        description: 'A mix of bone and meat pieces for rich curries.',
        price: 800,
        stock: 12,
        categoryId: 'meat-seafood',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-mutton-curry-cut')!.imageUrl,
        imageHint: 'mutton curry cut',
        sellerId: 'seller-1',
        subCategory: 'Mutton & Lamb (Aattu Iraichi)',
        tags: ['Halaal'],
    },
    {
        id: 'prod-mutton-keema',
        name: 'Mutton Keema',
        description: 'Finely minced mutton for various preparations.',
        price: 900,
        stock: 8,
        categoryId: 'meat-seafood',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-mutton-keema')!.imageUrl,
        imageHint: 'mutton mince',
        sellerId: 'seller-1',
        subCategory: 'Mutton & Lamb (Aattu Iraichi)',
    },
    {
        id: 'prod-seer-fish',
        name: 'Seer Fish (Vanjaram)',
        description: 'Freshly caught seer fish, perfect for frying.',
        price: 950,
        stock: 7,
        categoryId: 'meat-seafood',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-seer-fish')!.imageUrl,
        imageHint: 'seer fish',
        sellerId: 'seller-1',
        subCategory: 'Fresh Seafood (Meen Vagaigal)',
        tags: ['Fresh Catch'],
        cleaningOptions: [
            { id: 'seer-whole', type: 'Whole' },
            { id: 'seer-slices', type: 'Slices', priceModifier: 50 },
        ],
    },
    {
        id: 'prod-prawns',
        name: 'Prawns (Iral)',
        description: 'Juicy prawns, cleaned and deveined.',
        price: 600,
        stock: 18,
        categoryId: 'meat-seafood',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-prawns')!.imageUrl,
        imageHint: 'cleaned prawns',
        sellerId: 'seller-1',
        subCategory: 'Fresh Seafood (Meen Vagaigal)',
        tags: ['Fresh Catch'],
        cleaningOptions: [
            { id: 'prawns-whole', type: 'Whole' },
            { id: 'prawns-cleaned', type: 'Cleaned & Gutted', priceModifier: 80 },
        ],
    },
     {
        id: 'prod-salmon',
        name: 'Atlantic Salmon Fillet',
        description: 'Premium Atlantic Salmon, rich in Omega-3.',
        price: 1200,
        stock: 10,
        categoryId: 'meat-seafood',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-salmon')!.imageUrl,
        imageHint: 'salmon fillet',
        sellerId: 'seller-1',
        subCategory: 'Fresh Seafood (Meen Vagaigal)',
        tags: ['Fresh Catch'],
        cleaningOptions: [
            { id: 'salmon-whole', type: 'Whole' },
            { id: 'salmon-skin-off', type: 'Skin-off', priceModifier: 100 },
        ],
    },
    {
        id: 'prod-chicken-sausages',
        name: 'Chicken Sausages',
        description: 'Ready-to-cook chicken sausages.',
        price: 250,
        stock: 30,
        categoryId: 'meat-seafood',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-chicken-sausages')!.imageUrl,
        imageHint: 'chicken sausages',
        sellerId: 'seller-2',
        subCategory: 'Cold Cuts & Ready-to-Cook',
    },
    {
        id: 'prod-chicken-nuggets',
        name: 'Chicken Nuggets',
        description: 'Crispy and delicious chicken nuggets.',
        price: 280,
        stock: 25,
        categoryId: 'meat-seafood',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-chicken-nuggets')!.imageUrl,
        imageHint: 'chicken nuggets',
        sellerId: 'seller-2',
        subCategory: 'Cold Cuts & Ready-to-Cook',
    },
    {
        id: 'prod-quail-eggs',
        name: 'Quail Eggs (Kaadai Muttai)',
        description: 'Small and nutritious quail eggs.',
        price: 80,
        stock: 50,
        categoryId: 'meat-seafood',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-quail-eggs')!.imageUrl,
        imageHint: 'quail eggs',
        sellerId: 'seller-1',
        subCategory: 'Eggs',
    },
    
    // Prepared Foods
    {
        id: 'prod-paneer-butter-masala-rte',
        name: 'Paneer Butter Masala (Heat & Eat)',
        description: 'A classic creamy tomato and paneer curry, ready in minutes.',
        price: 180,
        stock: 40,
        categoryId: 'prepared-foods',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-paneer-butter-masala-rte')!.imageUrl,
        imageHint: 'paneer butter masala',
        sellerId: 'seller-3',
        subCategory: 'Instant Heat & Eat',
        serves: '1-2 people',
        cookingMethods: ['Microwave', 'Pan Fry'],
        tags: ['No Preservatives'],
        pairingIds: ['prod-chapati', 'prod-basmati-rice']
    },
    {
        id: 'prod-sambar-rice-rte',
        name: 'Sambar Sadam (Heat & Eat)',
        description: 'Homestyle sambar rice, just heat and serve.',
        price: 120,
        stock: 50,
        categoryId: 'prepared-foods',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-sambar-rice-rte')!.imageUrl,
        imageHint: 'sambar rice',
        sellerId: 'seller-3',
        subCategory: 'Instant Heat & Eat',
        serves: '1 person',
        cookingMethods: ['Microwave'],
    },
    {
        id: 'prod-veg-biryani-rte',
        name: 'Vegetable Biryani Tray',
        description: 'Aromatic vegetable biryani, perfect for a quick meal.',
        price: 150,
        stock: 30,
        categoryId: 'prepared-foods',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-veg-biryani-rte')!.imageUrl,
        imageHint: 'vegetable biryani',
        sellerId: 'seller-3',
        subCategory: 'Instant Heat & Eat',
        serves: '1-2 people',
        cookingMethods: ['Microwave'],
    },
    {
        id: 'prod-idli-dosa-batter',
        name: 'Idli & Dosa Batter',
        description: 'Freshly ground batter for soft idlis and crispy dosas.',
        price: 70,
        stock: 100,
        categoryId: 'prepared-foods',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-idli-dosa-batter')!.imageUrl,
        imageHint: 'dosa batter',
        sellerId: 'seller-3',
        subCategory: 'Batter & Mixes',
        serves: 'Family Pack',
        tags: ['No Preservatives'],
    },
    {
        id: 'prod-gulab-jamun-mix',
        name: 'Gulab Jamun Instant Mix',
        description: 'Make delicious gulab jamuns at home effortlessly.',
        price: 110,
        stock: 80,
        categoryId: 'prepared-foods',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-gulab-jamun-mix')!.imageUrl,
        imageHint: 'gulab jamun',
        sellerId: 'seller-3',
        subCategory: 'Batter & Mixes',
    },
    {
        id: 'prod-veg-cutlet-frozen',
        name: 'Vegetable Cutlet (Frozen)',
        description: 'Crispy vegetable patties, ready to fry or bake.',
        price: 150,
        stock: 60,
        categoryId: 'prepared-foods',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-veg-cutlet-frozen')!.imageUrl,
        imageHint: 'vegetable cutlet',
        sellerId: 'seller-2',
        subCategory: 'Frozen Snacks & Appetizers',
        cookingMethods: ['Deep Fry', 'Air Fryer'],
        serves: 'Approx. 10 pieces',
    },
     {
        id: 'prod-fish-fingers-frozen',
        name: 'Fish Fingers (Frozen)',
        description: 'Crispy breaded fish fingers, a perfect snack.',
        price: 220,
        stock: 40,
        categoryId: 'prepared-foods',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-fish-fingers')!.imageUrl,
        imageHint: 'fish fingers',
        sellerId: 'seller-2',
        subCategory: 'Frozen Snacks & Appetizers',
        cookingMethods: ['Deep Fry', 'Air Fryer'],
    },
    {
        id: 'prod-french-fries-frozen',
        name: 'French Fries (Frozen)',
        description: 'Classic potato french fries, ready for the fryer.',
        price: 120,
        stock: 90,
        categoryId: 'prepared-foods',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-french-fries-frozen')!.imageUrl,
        imageHint: 'french fries',
        sellerId: 'seller-2',
        subCategory: 'Frozen Snacks & Appetizers',
        cookingMethods: ['Deep Fry', 'Air Fryer'],
    },
    {
        id: 'prod-gobi-manchurian-rtc',
        name: 'Gobi Manchurian Mix (Ready-to-Cook)',
        description: 'Marinated cauliflower florets for perfect Gobi Manchurian.',
        price: 130,
        stock: 45,
        categoryId: 'prepared-foods',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-gobi-manchurian-rtc')!.imageUrl,
        imageHint: 'gobi manchurian',
        sellerId: 'seller-3',
        subCategory: 'Gourmet Ready-to-Cook',
        cookingMethods: ['Pan Fry'],
        serves: '2 people',
    },
    {
        id: 'prod-paneer-tikka-rtc',
        name: 'Paneer Tikka Skewers (Ready-to-Cook)',
        description: 'Marinated paneer and vegetable skewers, ready for the grill.',
        price: 220,
        stock: 35,
        categoryId: 'prepared-foods',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-paneer-tikka-rtc')!.imageUrl,
        imageHint: 'paneer tikka',
        sellerId: 'seller-3',
        subCategory: 'Gourmet Ready-to-Cook',
        cookingMethods: ['Grill', 'Pan Fry'],
        serves: '2-3 people',
        tags: ['High Protein'],
        pairingIds: ['prod-mint-chutney']
    },
    {
        id: 'prod-mini-tiffin-deli',
        name: 'Mini Tiffin Combo',
        description: 'A perfect breakfast combo with Idli, Vada, and Pongal.',
        price: 100,
        stock: 50,
        categoryId: 'prepared-foods',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-mini-tiffin-deli')!.imageUrl,
        imageHint: 'tiffin combo',
        sellerId: 'seller-3',
        subCategory: 'Deli & Freshly Prepared',
        serves: '1 person',
        tags: ['No Preservatives']
    },
    {
        id: 'prod-curd-rice-deli',
        name: 'Curd Rice with Pickle',
        description: 'Comforting curd rice served with a side of traditional pickle.',
        price: 80,
        stock: 60,
        categoryId: 'prepared-foods',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-curd-rice-deli')!.imageUrl,
        imageHint: 'curd rice',
        sellerId: 'seller-3',
        subCategory: 'Deli & Freshly Prepared',
        serves: '1 person',
    },
    {
        id: 'prod-mint-chutney',
        name: 'Mint Chutney',
        description: 'Fresh and tangy mint chutney, perfect with snacks.',
        price: 40,
        stock: 80,
        categoryId: 'prepared-foods',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-mint-chutney')!.imageUrl,
        imageHint: 'mint chutney',
        sellerId: 'seller-3',
        subCategory: 'Deli & Freshly Prepared',
    },

    // Snacks
    {
        id: 'prod-murukku',
        name: 'Murukku',
        description: 'Classic crunchy spiral snack made from rice flour.',
        price: 80,
        stock: 100,
        categoryId: 'snacks',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-murukku')!.imageUrl,
        imageHint: 'murukku snack',
        sellerId: 'seller-3',
        subCategory: 'Savory Snacks',
    },
    {
        id: 'prod-thattai',
        name: 'Thattai',
        description: 'Crispy and savory flat discs, perfect with tea.',
        price: 75,
        stock: 90,
        categoryId: 'snacks',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-thattai')!.imageUrl,
        imageHint: 'thattai snack',
        sellerId: 'seller-3',
        subCategory: 'Savory Snacks',
    },
    {
        id: 'prod-mixture',
        name: 'South Indian Mixture',
        description: 'A delightful mix of various fried snacks and nuts.',
        price: 120,
        stock: 80,
        categoryId: 'snacks',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-mixture')!.imageUrl,
        imageHint: 'mixture snack',
        sellerId: 'seller-3',
        subCategory: 'Savory Snacks',
    },
    {
        id: 'prod-ribbon-pakoda',
        name: 'Ribbon Pakoda',
        description: 'Crispy ribbon-shaped snack made from gram flour.',
        price: 85,
        stock: 110,
        categoryId: 'snacks',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-ribbon-pakoda')!.imageUrl,
        imageHint: 'ribbon pakoda',
        sellerId: 'seller-3',
        subCategory: 'Savory Snacks',
    },
    {
        id: 'prod-kadalai-mittai',
        name: 'Kadalai Mittai (Groundnut Chikki)',
        description: 'Traditional groundnut and jaggery candy.',
        price: 50,
        stock: 150,
        categoryId: 'snacks',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-kadalai-mittai')!.imageUrl,
        imageHint: 'groundnut candy',
        sellerId: 'seller-3',
        subCategory: 'Sweets',
    },
    {
        id: 'prod-adhirasam',
        name: 'Adhirasam',
        description: 'A traditional sweet pastry from Tamil cuisine.',
        price: 120,
        stock: 60,
        categoryId: 'snacks',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-adhirasam')!.imageUrl,
        imageHint: 'adhirasam sweet',
        sellerId: 'seller-3',
        subCategory: 'Sweets',
    },
    {
        id: 'prod-halwa',
        name: 'Tirunelveli Halwa',
        description: 'A rich, ghee-laden wheat halwa.',
        price: 180,
        stock: 40,
        categoryId: 'snacks',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-halwa')!.imageUrl,
        imageHint: 'tirunelveli halwa',
        sellerId: 'seller-3',
        subCategory: 'Sweets',
    },

    // Beverages
    {
        id: 'prod-tea',
        name: 'Assam Black Tea',
        description: 'Strong and malty black tea.',
        price: 250,
        stock: 100,
        categoryId: 'beverages',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-tea')!.imageUrl,
        imageHint: 'tea box',
        sellerId: 'seller-3',
        subCategory: 'Tea & Coffee',
    },
    {
        id: 'prod-coffee',
        name: 'Instant Filter Coffee',
        description: 'Aromatic South Indian filter coffee.',
        price: 350,
        stock: 80,
        categoryId: 'beverages',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-coffee')!.imageUrl,
        imageHint: 'coffee jar',
        sellerId: 'seller-3',
        subCategory: 'Tea & Coffee',
    },
    {
        id: 'prod-coke',
        name: 'Coca-Cola Can',
        description: 'Classic and refreshing Coca-Cola.',
        price: 40,
        stock: 200,
        categoryId: 'beverages',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-coke')!.imageUrl,
        imageHint: 'coke can',
        sellerId: 'seller-2',
        subCategory: 'Soft Drinks & Juices',
    },
    {
        id: 'prod-juice',
        name: 'Real Orange Juice',
        description: 'Packaged orange juice, rich in Vitamin C.',
        price: 120,
        stock: 150,
        categoryId: 'beverages',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-juice')!.imageUrl,
        imageHint: 'juice carton',
        sellerId: 'seller-2',
        subCategory: 'Soft Drinks & Juices',
    },
    {
        id: 'prod-bournvita',
        name: 'Bournvita Health Drink',
        description: 'Chocolate-flavored health drink for all ages.',
        price: 280,
        stock: 100,
        categoryId: 'beverages',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-bournvita')!.imageUrl,
        imageHint: 'bournvita jar',
        sellerId: 'seller-3',
        subCategory: 'Health Drinks',
    },
    {
        id: 'prod-redbull',
        name: 'Red Bull Energy Drink',
        description: 'Gives you wings.',
        price: 125,
        stock: 90,
        categoryId: 'beverages',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-redbull')!.imageUrl,
        imageHint: 'red bull',
        sellerId: 'seller-2',
        subCategory: 'Energy Drinks',
    },
];

const users: User[] = [
  { id: 'user-1', name: 'Alice', email: 'alice@example.com', role: 'Customer' },
  { id: 'admin-1', name: 'Admin User', email: 'admin@example.com', role: 'Admin' },
  { id: 'delivery-1', name: 'Bob', email: 'bob@example.com', role: 'Delivery' },
  { id: 'seller-1', name: 'FarmFresh Organics', email: 'contact@farmfresh.com', role: 'Seller' },
  { id: 'seller-2', name: 'Artisan Bakery', email: 'hello@artisanbakery.com', role: 'Seller' },
  { id: 'seller-3', name: 'Amma\'s Kitchen', email: 'support@ammaskitchen.com', role: 'Seller' },
];

const reviews: Review[] = [
  { id: 'rev-1', productId: 'prod-apple', userId: 'user-1', rating: 5, comment: 'These apples are incredibly fresh and crisp!', timestamp: '2023-10-26T10:00:00Z' },
  { id: 'rev-2', productId: 'prod-apple', userId: 'user-2', rating: 4, comment: 'Good quality, but a bit pricey.', timestamp: '2023-10-25T14:30:00Z' },
  { id: 'rev-3', productId: 'prod-idli-dosa-batter', userId: 'user-1', rating: 5, comment: 'Tasted just like homemade. Excellent!', timestamp: '2023-10-24T18:00:00Z' },
  { id: 'rev-4', productId: 'prod-milk-pouch', userId: 'user-1', rating: 5, comment: 'Aavin milk is always reliable.', timestamp: '2024-07-15T08:00:00Z' },
  { id: 'rev-5', productId: 'prod-chicken-curry-cut', userId: 'user-1', rating: 4, comment: 'Chicken was fresh but pieces were a bit small.', timestamp: '2024-07-14T19:30:00Z' },
];

const orders: Order[] = [
    {
        id: 'order-1',
        userId: 'user-1',
        items: [
            { productId: 'prod-apple', quantity: 2, price: 150 },
            { productId: 'prod-milk-pouch', quantity: 1, price: 22 }
        ],
        totalAmount: 322,
        status: 'Delivered',
        deliveryAddress: {
            name: 'Alice',
            address: '123 Green St',
            city: 'Chennai',
            zip: '600001'
        },
        timestamp: '2024-07-15T10:00:00Z'
    },
    {
        id: 'order-2',
        userId: 'admin-1', // Assuming admin can also be a customer
        items: [
            { productId: 'prod-idli-dosa-batter', quantity: 2, price: 70 },
            { productId: 'prod-coke', quantity: 4, price: 40 }
        ],
        totalAmount: 300,
        status: 'Processing',
        deliveryAddress: {
            name: 'Admin User',
            address: '456 Park Ave',
            city: 'Chennai',
            zip: '600008'
        },
        timestamp: '2024-07-20T11:30:00Z'
    },
     {
        id: 'order-3',
        userId: 'user-1',
        items: [
            { productId: 'prod-mutton-curry-cut', quantity: 1, price: 800 },
            { productId: 'prod-basmati-rice', quantity: 1, price: 180, variantId: 'prod-basmati-rice-1kg' },
        ],
        totalAmount: 980,
        status: 'Out for Delivery',
        deliveryAddress: {
            name: 'Alice',
            address: '123 Green St',
            city: 'Chennai',
            zip: '600001'
        },
        timestamp: '2024-07-21T09:00:00Z'
    }
];

export const getCategories = () => categories;
export const getProducts = () => products;
export const getFeaturedProducts = () => products.slice(0, 4);
export const getProductById = (id: string) => products.find(p => p.id === id);
export const getProductsByCategory = (categoryId: string) => products.filter(p => p.categoryId === categoryId);
export const getProductsBySeller = (sellerId: string) => products.filter(p => p.sellerId === sellerId);

export const getUsers = () => users;
export const getUserById = (id: string) => users.find(u => u.id === id);

export const getReviews = () => reviews;
export const getReviewsForProduct = (productId: string) => reviews.filter(r => r.productId === productId);

export const getOrders = () => orders;
export const getOrderById = (id: string) => orders.find(o => o.id === id);
export const getOrdersByUser = (userId: string) => orders.filter(o => o.userId === userId);
