
import type { Product, Category, User, Review, Order } from './types';
import { PlaceHolderImages } from './placeholder-images';

const categories: Category[] = [
    // Grocery
    { id: 'fresh-produce', name: 'Fresh Produce', description: 'Fresh fruits and vegetables.', productType: 'grocery' },
    { id: 'dairy-eggs', name: 'Dairy & Eggs', description: 'Milk, cheese, eggs, and more.', productType: 'grocery' },
    { id: 'staples-grains', name: 'Staples & Grains', description: 'Rice, flour, dals, and other essentials.', productType: 'grocery' },
    { id: 'spices-masalas', name: 'Spices & Masalas', description: 'Aromatic spices and masalas.', productType: 'grocery' },
    { id: 'bakery-breakfast', name: 'Bakery & Breakfast', description: 'Bread, biscuits, cereals, and spreads.', productType: 'grocery' },
    { id: 'cooking-oils-ghee', name: 'Cooking Oils & Ghee', description: 'Essential cooking oils and ghee.', productType: 'grocery' },
    { id: 'packaged-instant-foods', name: 'Packaged & Instant Foods', description: 'Noodles, ready-to-eat meals, and more.', productType: 'grocery' },
    { id: 'snacks-beverages', name: 'Snacks & Beverages', description: 'Chips, chocolates, drinks, and more.', productType: 'grocery' },
    { id: 'personal-care-wellness', name: 'Personal Care & Wellness', description: 'Health and beauty products.', productType: 'grocery' },
    { id: 'household-essentials', name: 'Household Essentials', description: 'Cleaning supplies and other home needs.', productType: 'grocery' },
    { id: 'meat-seafood', name: 'Meat & Seafood', description: 'Fresh meat and seafood items.', productType: 'grocery' },
    
    // Food Delivery
    { id: 'fast-food', name: 'Fast Food', description: 'Burgers, Pizza, Fries and more.', productType: 'food' },
    { id: 'main-course', name: 'Main Course', description: 'South Indian, North Indian, Chinese, and more.', productType: 'food' },
    { id: 'healthy-diet-food', name: 'Healthy & Diet Food', description: 'Salads, low-calorie meals, and more.', productType: 'food' },
    { id: 'street-food', name: 'Street Food', description: 'Chaats, rolls, sandwiches, and more.', productType: 'food' },
    { id: 'bakery-desserts', name: 'Bakery & Desserts', description: 'Cakes, pastries, ice creams, and more.', productType: 'food' },
    { id: 'beverages', name: 'Beverages', description: 'Fresh juices, milkshakes, smoothies, and more.', productType: 'food' },

    // E-Commerce
    { id: 'electronics', name: 'Electronics', description: 'Mobiles, accessories, and smart gadgets.', productType: 'ecommerce' },
    { id: 'fashion', name: 'Fashion', description: 'Clothing for men, women, and kids.', productType: 'ecommerce' },
    { id: 'footwear', name: 'Footwear', description: 'Casual shoes, sports shoes, and sandals.', productType: 'ecommerce' },
    { id: 'accessories', name: 'Accessories', description: 'Bags, watches, and sunglasses.', productType: 'ecommerce' },
    { id: 'home-kitchen', name: 'Home & Kitchen', description: 'Cookware, storage, and home decor.', productType: 'ecommerce' },
    { id: 'beauty-personal-care', name: 'Beauty & Personal Care', description: 'Makeup, skin care, and hair styling tools.', productType: 'ecommerce' },
    { id: 'baby-kids', name: 'Baby & Kids', description: 'Toys and baby essentials.', productType: 'ecommerce' },
];

const products: Product[] = [
    // Fresh Produce
    {
        id: 'prod-potato',
        name: 'Potato (Aloo)',
        description: 'Versatile and essential for many dishes.',
        price: 30,
        stock: 100,
        productType: 'grocery',
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-potato')!.imageUrl,
        imageHint: 'fresh potatoes',
        sellerId: 'seller-1',
        subCategory: 'Vegetables',
        variants: [
            { id: 'prod-potato-500g', weight: '500g', price: 15, stock: 50 },
            { id: 'prod-potato-1kg', weight: '1kg', price: 30, stock: 30 },
            { id: 'prod-potato-5kg', weight: '5kg', price: 140, stock: 20 },
        ],
    },
    {
        id: 'prod-onion',
        name: 'Onion (Vengayam)',
        description: 'A staple in every Indian kitchen.',
        price: 40,
        stock: 80,
        productType: 'grocery',
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-onion')!.imageUrl,
        imageHint: 'fresh onions',
        sellerId: 'seller-1',
        subCategory: 'Vegetables',
         variants: [
            { id: 'prod-onion-500g', weight: '500g', price: 20, stock: 40 },
            { id: 'prod-onion-1kg', weight: '1kg', price: 40, stock: 30 },
            { id: 'prod-onion-5kg', weight: '5kg', price: 190, stock: 10 },
        ],
    },
    {
        id: 'prod-tomato',
        name: 'Tomato (Thakkali)',
        description: 'Ripe and juicy tomatoes.',
        price: 25,
        stock: 120,
        productType: 'grocery',
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-tomato')!.imageUrl,
        imageHint: 'ripe tomatoes',
        sellerId: 'seller-1',
        subCategory: 'Vegetables',
        variants: [
            { id: 'prod-tomato-500g', weight: '500g', price: 13, stock: 60 },
            { id: 'prod-tomato-1kg', weight: '1kg', price: 25, stock: 60 },
        ],
    },
    {
        id: 'prod-spinach',
        name: 'Spinach (Palak)',
        description: 'Freshly picked leafy greens.',
        price: 20,
        stock: 50,
        productType: 'grocery',
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-spinach')!.imageUrl,
        imageHint: 'spinach leaves',
        sellerId: 'seller-1',
        subCategory: 'Leafy Greens',
    },
    {
        id: 'prod-coriander',
        name: 'Coriander (Kothamalli)',
        description: 'Aromatic and fresh coriander bunches.',
        price: 15,
        stock: 70,
        productType: 'grocery',
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-coriander')!.imageUrl,
        imageHint: 'coriander bunch',
        sellerId: 'seller-1',
        subCategory: 'Leafy Greens',
    },
    {
        id: 'prod-mint',
        name: 'Mint (Pudina)',
        description: 'Refreshing mint leaves.',
        price: 10,
        stock: 80,
        productType: 'grocery',
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-mint')!.imageUrl,
        imageHint: 'mint leaves',
        sellerId: 'seller-1',
        subCategory: 'Leafy Greens',
    },
    {
        id: 'prod-curry-leaves',
        name: 'Curry Leaves (Karuveppilai)',
        description: 'Essential for tempering South Indian dishes.',
        price: 8,
        stock: 100,
        productType: 'grocery',
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-curry-leaves')!.imageUrl,
        imageHint: 'curry leaves',
        sellerId: 'seller-1',
        subCategory: 'Leafy Greens',
    },
     {
        id: 'prod-mango',
        name: 'Mango',
        description: 'Sweet and juicy seasonal mangoes.',
        price: 120,
        stock: 40,
        productType: 'grocery',
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-mangoes')!.imageUrl,
        imageHint: 'ripe mangoes',
        sellerId: 'seller-1',
        subCategory: 'Fruits',
    },
    {
        id: 'prod-watermelon',
        name: 'Watermelon',
        description: 'Refreshing and hydrating watermelon.',
        price: 80,
        stock: 30,
        productType: 'grocery',
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-watermelon')!.imageUrl,
        imageHint: 'watermelon slice',
        sellerId: 'seller-1',
        subCategory: 'Fruits',
    },
    {
        id: 'prod-grapes',
        name: 'Grapes',
        description: 'Sweet and crisp green grapes.',
        price: 90,
        stock: 60,
        productType: 'grocery',
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-grapes')!.imageUrl,
        imageHint: 'green grapes',
        sellerId: 'seller-1',
        subCategory: 'Fruits',
    },
    {
        id: 'prod-oranges',
        name: 'Oranges',
        description: 'Juicy and vitamin C-rich oranges.',
        price: 100,
        stock: 50,
        productType: 'grocery',
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-oranges')!.imageUrl,
        imageHint: 'fresh oranges',
        sellerId: 'seller-1',
        subCategory: 'Fruits',
    },
    {
        id: 'prod-apple',
        name: 'Apple',
        description: 'Crisp and delicious red apples.',
        price: 150,
        stock: 80,
        productType: 'grocery',
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-apple')!.imageUrl,
        imageHint: 'red apples',
        sellerId: 'seller-1',
        subCategory: 'Fruits',
    },
    {
        id: 'prod-banana',
        name: 'Banana',
        description: 'A bunch of ripe Yelakki bananas.',
        price: 40,
        stock: 100,
        productType: 'grocery',
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-banana')!.imageUrl,
        imageHint: 'ripe bananas',
        sellerId: 'seller-1',
        subCategory: 'Fruits',
    },
    {
        id: 'prod-broccoli',
        name: 'Broccoli',
        description: 'Fresh green broccoli florets.',
        price: 60,
        stock: 40,
        productType: 'grocery',
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-broccoli')!.imageUrl,
        imageHint: 'fresh broccoli',
        sellerId: 'seller-1',
        subCategory: 'Vegetables',
    },
    {
        id: 'prod-bell-peppers',
        name: 'Bell Peppers (Capsicum)',
        description: 'A mix of colorful bell peppers.',
        price: 70,
        stock: 50,
        productType: 'grocery',
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-bell-peppers')!.imageUrl,
        imageHint: 'bell peppers',
        sellerId: 'seller-1',
        subCategory: 'Vegetables',
    },
    {
        id: 'prod-zucchini',
        name: 'Zucchini',
        description: 'Tender and fresh zucchini.',
        price: 50,
        stock: 30,
        productType: 'grocery',
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-zucchini')!.imageUrl,
        imageHint: 'fresh zucchini',
        sellerId: 'seller-1',
        subCategory: 'Vegetables',
    },
    {
        id: 'prod-lettuce',
        name: 'Lettuce',
        description: 'Crisp and fresh lettuce head.',
        price: 45,
        stock: 40,
        productType: 'grocery',
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-lettuce')!.imageUrl,
        imageHint: 'lettuce head',
        sellerId: 'seller-1',
        subCategory: 'Leafy Greens',
    },
    {
        id: 'prod-avocado',
        name: 'Avocado',
        description: 'Creamy and ripe avocados.',
        price: 120,
        stock: 25,
        productType: 'grocery',
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-avocado')!.imageUrl,
        imageHint: 'ripe avocado',
        sellerId: 'seller-1',
        subCategory: 'Fruits',
    },
    {
        id: 'prod-peeled-garlic',
        name: 'Peeled Garlic',
        description: 'Conveniently peeled garlic cloves.',
        price: 50,
        stock: 60,
        productType: 'grocery',
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-peeled-garlic')!.imageUrl,
        imageHint: 'peeled garlic',
        sellerId: 'seller-1',
        subCategory: 'Vegetables',
    },
    {
        id: 'prod-sambhar-mix',
        name: 'Chopped Sambhar Mix',
        description: 'A mix of vegetables for sambhar.',
        price: 40,
        stock: 40,
        productType: 'grocery',
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-sambhar-mix')!.imageUrl,
        imageHint: 'chopped vegetables',
        sellerId: 'seller-1',
        subCategory: 'Vegetables',
    },
    {
        id: 'prod-sprouted-moong',
        name: 'Sprouted Moong Dal',
        description: 'Healthy and ready-to-use sprouted moong.',
        price: 35,
        stock: 50,
        productType: 'grocery',
        categoryId: 'staples-grains',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-sprouted-moong')!.imageUrl,
        imageHint: 'sprouted moong',
        sellerId: 'seller-1',
        subCategory: 'Pulses & Lentils',
    },
    {
        id: 'prod-grated-coconut',
        name: 'Grated Coconut',
        description: 'Freshly grated coconut for your recipes.',
        price: 30,
        stock: 70,
        productType: 'grocery',
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-grated-coconut')!.imageUrl,
        imageHint: 'grated coconut',
        sellerId: 'seller-1',
        subCategory: 'Fruits',
    },
    {
        id: 'prod-veggie-combo',
        name: 'Onion-Potato-Tomato Combo',
        description: 'A convenient combo of kitchen staples.',
        price: 85,
        stock: 30,
        productType: 'grocery',
        categoryId: 'fresh-produce',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-veggie-combo')!.imageUrl,
        imageHint: 'vegetable combo',
        sellerId: 'seller-1',
        subCategory: 'Vegetables',
    },

    // Dairy & Eggs
    {
        id: 'prod-milk-pouch',
        name: 'Aavin Toned Milk',
        description: 'Fresh toned milk from Aavin.',
        price: 22,
        stock: 150,
        productType: 'grocery',
        categoryId: 'dairy-eggs',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-milk-pouch')!.imageUrl,
        imageHint: 'milk pouch',
        sellerId: 'seller-1',
        subCategory: 'Milk & Curd',
        brand: 'Aavin',
    },
    {
        id: 'prod-milk-pouch-full',
        name: 'Heritage Full Cream Milk',
        description: 'Rich and creamy full cream milk.',
        price: 32,
        stock: 100,
        productType: 'grocery',
        categoryId: 'dairy-eggs',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-milk-pouch-full')!.imageUrl,
        imageHint: 'milk pouch',
        sellerId: 'seller-1',
        subCategory: 'Milk & Curd',
        brand: 'Heritage',
    },
    {
        id: 'prod-buttermilk',
        name: 'Spiced Buttermilk (Neer Mor)',
        description: 'Refreshing and traditional buttermilk.',
        price: 15,
        stock: 80,
        productType: 'grocery',
        categoryId: 'dairy-eggs',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-buttermilk')!.imageUrl,
        imageHint: 'buttermilk glass',
        sellerId: 'seller-2',
        subCategory: 'Milk & Curd',
    },
    {
        id: 'prod-curd',
        name: 'Fresh Curd (Thayir)',
        description: 'Thick and creamy homemade style curd.',
        price: 40,
        stock: 120,
        productType: 'grocery',
        categoryId: 'dairy-eggs',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-curd')!.imageUrl,
        imageHint: 'curd bowl',
        sellerId: 'seller-1',
        subCategory: 'Milk & Curd',
    },
    {
        id: 'prod-butter',
        name: 'Amul Salted Butter',
        description: 'Classic salted butter for all your needs.',
        price: 55,
        stock: 90,
        productType: 'grocery',
        categoryId: 'dairy-eggs',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-butter')!.imageUrl,
        imageHint: 'butter block',
        sellerId: 'seller-1',
        subCategory: 'Butter & Cheese',
        brand: 'Amul',
    },
    {
        id: 'prod-cheese',
        name: 'Cheese Slices',
        description: 'Perfect for sandwiches and burgers.',
        price: 120,
        stock: 70,
        productType: 'grocery',
        categoryId: 'dairy-eggs',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-cheese')!.imageUrl,
        imageHint: 'cheese slices',
        sellerId: 'seller-2',
        subCategory: 'Butter & Cheese',
    },
    {
        id: 'prod-paneer',
        name: 'Fresh Paneer',
        description: 'Soft cottage cheese for curries and snacks.',
        price: 90,
        stock: 60,
        productType: 'grocery',
        categoryId: 'dairy-eggs',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-paneer')!.imageUrl,
        imageHint: 'paneer cubes',
        sellerId: 'seller-2',
        subCategory: 'Paneer',
    },
    {
        id: 'prod-eggs-white',
        name: 'White Eggs',
        description: 'Farm-fresh white eggs.',
        price: 72,
        stock: 200,
        productType: 'grocery',
        categoryId: 'dairy-eggs',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-eggs-white')!.imageUrl,
        imageHint: 'carton eggs',
        sellerId: 'seller-1',
        subCategory: 'Eggs',
        variants: [
            { id: 'prod-eggs-white-6', weight: '6 pack', price: 36, stock: 100 },
            { id: 'prod-eggs-white-12', weight: '12 pack', price: 72, stock: 100 },
        ],
    },
    {
        id: 'prod-eggs-brown',
        name: 'Brown Eggs',
        description: 'Free-range brown eggs.',
        price: 90,
        stock: 150,
        productType: 'grocery',
        categoryId: 'dairy-eggs',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-eggs-brown')!.imageUrl,
        imageHint: 'brown eggs',
        sellerId: 'seller-1',
        subCategory: 'Eggs',
        variants: [
            { id: 'prod-eggs-brown-6', weight: '6 pack', price: 45, stock: 75 },
            { id: 'prod-eggs-brown-12', weight: '12 pack', price: 90, stock: 75 },
        ],
    },

    // Staples & Grains
    {
        id: 'prod-ponni-rice',
        name: 'Ponni Rice',
        description: 'High-quality Ponni rice for daily meals.',
        price: 550,
        stock: 50,
        productType: 'grocery',
        categoryId: 'staples-grains',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-rice-bag')!.imageUrl,
        imageHint: 'rice bag',
        sellerId: 'seller-3',
        subCategory: 'Rice',
        variants: [
            { id: 'prod-ponni-rice-1kg', weight: '1kg', price: 60, stock: 20 },
            { id: 'prod-ponni-rice-5kg', weight: '5kg', price: 280, stock: 20 },
            { id: 'prod-ponni-rice-10kg', weight: '10kg', price: 550, stock: 10 },
        ],
    },
    {
        id: 'prod-basmati-rice',
        name: 'Basmati Rice',
        description: 'Aromatic long-grain Basmati rice for biryani.',
        price: 180,
        stock: 40,
        productType: 'grocery',
        categoryId: 'staples-grains',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-basmati-rice')!.imageUrl,
        imageHint: 'basmati rice',
        sellerId: 'seller-3',
        subCategory: 'Rice',
        variants: [
            { id: 'prod-basmati-rice-1kg', weight: '1kg', price: 180, stock: 20 },
            { id: 'prod-basmati-rice-5kg', weight: '5kg', price: 850, stock: 20 },
        ],
    },
    {
        id: 'prod-idli-rice',
        name: 'Idli Rice',
        description: 'Special parboiled rice for soft idlis.',
        price: 50,
        stock: 60,
        productType: 'grocery',
        categoryId: 'staples-grains',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-idli-rice')!.imageUrl,
        imageHint: 'rice grains',
        sellerId: 'seller-3',
        subCategory: 'Rice',
        variants: [
            { id: 'prod-idli-rice-1kg', weight: '1kg', price: 50, stock: 30 },
            { id: 'prod-idli-rice-5kg', weight: '5kg', price: 240, stock: 30 },
        ],
    },
    {
        id: 'prod-poha',
        name: 'Poha (Aval)',
        description: 'Flattened rice for quick breakfasts.',
        price: 40,
        stock: 100,
        productType: 'grocery',
        categoryId: 'bakery-breakfast',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-poha')!.imageUrl,
        imageHint: 'flattened rice',
        sellerId: 'seller-3',
        subCategory: 'Cereals & Oats',
    },
    {
        id: 'prod-atta',
        name: 'Whole Wheat Atta',
        description: 'Stone-ground whole wheat flour for rotis.',
        price: 250,
        stock: 80,
        productType: 'grocery',
        categoryId: 'staples-grains',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-atta')!.imageUrl,
        imageHint: 'atta flour',
        sellerId: 'seller-3',
        subCategory: 'Wheat & Atta',
        variants: [
            { id: 'prod-atta-1kg', weight: '1kg', price: 55, stock: 40 },
            { id: 'prod-atta-5kg', weight: '5kg', price: 250, stock: 40 },
        ],
    },
    {
        id: 'prod-besan',
        name: 'Besan (Gram Flour)',
        description: 'Fine gram flour for snacks and batters.',
        price: 70,
        stock: 90,
        productType: 'grocery',
        categoryId: 'staples-grains',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-besan')!.imageUrl,
        imageHint: 'gram flour',
        sellerId: 'seller-3',
        subCategory: 'Wheat & Atta',
    },
    {
        id: 'prod-rice-flour',
        name: 'Rice Flour',
        description: 'Fine rice flour for murukku and other snacks.',
        price: 45,
        stock: 70,
        productType: 'grocery',
        categoryId: 'staples-grains',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-rice-flour')!.imageUrl,
        imageHint: 'rice flour',
        sellerId: 'seller-3',
        subCategory: 'Rice',
    },
    {
        id: 'prod-ragi-flour',
        name: 'Ragi Flour (Finger Millet)',
        description: 'Nutritious finger millet flour.',
        price: 60,
        stock: 60,
        productType: 'grocery',
        categoryId: 'staples-grains',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-ragi-flour')!.imageUrl,
        imageHint: 'ragi flour',
        sellerId: 'seller-3',
        subCategory: 'Millets',
        tags: ['Low GI'],
    },
    {
        id: 'prod-toor-dal',
        name: 'Toor Dal (Sambar Paruppu)',
        description: 'Essential dal for making sambar.',
        price: 150,
        stock: 100,
        productType: 'grocery',
        categoryId: 'staples-grains',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-toor-dal')!.imageUrl,
        imageHint: 'toor dal',
        sellerId: 'seller-3',
        subCategory: 'Pulses & Lentils',
        tags: ['High Protein'],
    },
    {
        id: 'prod-urad-dal',
        name: 'Urad Dal (Split)',
        description: 'Split urad dal for batters and tempering.',
        price: 160,
        stock: 80,
        productType: 'grocery',
        categoryId: 'staples-grains',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-urad-dal')!.imageUrl,
        imageHint: 'urad dal',
        sellerId: 'seller-3',
        subCategory: 'Pulses & Lentils',
    },
     {
        id: 'prod-chickpeas',
        name: 'Kabuli Chana (Chickpeas)',
        description: 'High-quality chickpeas for various dishes.',
        price: 120,
        stock: 70,
        productType: 'grocery',
        categoryId: 'staples-grains',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-chickpeas')!.imageUrl,
        imageHint: 'chickpeas bowl',
        sellerId: 'seller-3',
        subCategory: 'Pulses & Lentils',
        tags: ['High Protein'],
    },
    {
        id: 'prod-crystal-salt',
        name: 'Crystal Salt (Kallu Uppu)',
        description: 'Coarse sea salt for traditional cooking.',
        price: 20,
        stock: 200,
        productType: 'grocery',
        categoryId: 'spices-masalas',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-crystal-salt')!.imageUrl,
        imageHint: 'crystal salt',
        sellerId: 'seller-3',
        subCategory: 'Salt & Sugar',
    },
    {
        id: 'prod-sugar',
        name: 'White Sugar',
        description: 'Refined white sugar.',
        price: 45,
        stock: 300,
        productType: 'grocery',
        categoryId: 'spices-masalas',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-sugar')!.imageUrl,
        imageHint: 'sugar cubes',
        sellerId: 'seller-3',
        subCategory: 'Salt & Sugar',
    },
    {
        id: 'prod-jaggery',
        name: 'Jaggery (Vellam)',
        description: 'Traditional unrefined cane sugar.',
        price: 80,
        stock: 100,
        productType: 'grocery',
        categoryId: 'spices-masalas',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-jaggery')!.imageUrl,
        imageHint: 'jaggery block',
        sellerId: 'seller-3',
        subCategory: 'Salt & Sugar',
    },
    {
        id: 'prod-barnyard-millet',
        name: 'Barnyard Millet (Kuthiraivali)',
        description: 'Healthy and versatile millet.',
        price: 90,
        stock: 50,
        productType: 'grocery',
        categoryId: 'staples-grains',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-barnyard-millet')!.imageUrl,
        imageHint: 'millet grains',
        sellerId: 'seller-3',
        subCategory: 'Millets',
        tags: ['Low GI'],
    },
    {
        id: 'prod-foxtail-millet',
        name: 'Foxtail Millet (Thinai)',
        description: 'Nutrient-rich foxtail millet.',
        price: 95,
        stock: 50,
        productType: 'grocery',
        categoryId: 'staples-grains',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-foxtail-millet')!.imageUrl,
        imageHint: 'foxtail millet',
        sellerId: 'seller-3',
        subCategory: 'Millets',
        tags: ['Low GI', 'High Protein'],
    },

    // Bakery & Breakfast
    {
        id: 'prod-bread',
        name: 'Sandwich Bread',
        description: 'Soft and fresh white bread.',
        price: 45,
        stock: 100,
        productType: 'grocery',
        categoryId: 'bakery-breakfast',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-bread')!.imageUrl,
        imageHint: 'sandwich bread',
        sellerId: 'seller-2',
        subCategory: 'Bread & Buns',
        bestBefore: '3 days',
    },
     {
        id: 'prod-chapati',
        name: 'Ready-made Chapati',
        description: 'Soft, ready-to-heat whole wheat chapatis.',
        price: 80,
        stock: 100,
        productType: 'grocery',
        categoryId: 'packaged-instant-foods',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-chapati')!.imageUrl,
        imageHint: 'chapati stack',
        sellerId: 'seller-2',
        subCategory: 'Ready-to-Eat Meals',
        bestBefore: '5 days',
    },
    {
        id: 'prod-rusk',
        name: 'Tea Rusk',
        description: 'Crispy and delicious tea-time rusks.',
        price: 60,
        stock: 80,
        productType: 'grocery',
        categoryId: 'bakery-breakfast',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-rusk')!.imageUrl,
        imageHint: 'tea rusk',
        sellerId: 'seller-2',
        subCategory: 'Biscuits & Cookies',
        bestBefore: '30 days',
    },
    {
        id: 'prod-oreo',
        name: 'Oreo Biscuits',
        description: 'The classic chocolate sandwich cookie.',
        price: 30,
        stock: 200,
        productType: 'grocery',
        categoryId: 'bakery-breakfast',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-oreo')!.imageUrl,
        imageHint: 'oreo biscuits',
        sellerId: 'seller-2',
        subCategory: 'Biscuits & Cookies',
    },
    {
        id: 'prod-marie-biscuit',
        name: 'Marie Gold Biscuits',
        description: 'Light and crisp tea-time biscuits.',
        price: 20,
        stock: 300,
        productType: 'grocery',
        categoryId: 'bakery-breakfast',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-marie-biscuit')!.imageUrl,
        imageHint: 'marie biscuits',
        sellerId: 'seller-2',
        subCategory: 'Biscuits & Cookies',
        pairingIds: ['prod-tea'],
    },

    // Meat & Seafood
    {
        id: 'prod-chicken-curry-cut',
        name: 'Chicken Curry Cut',
        description: 'Fresh, bone-in chicken pieces perfect for curries.',
        price: 250,
        stock: 20,
        productType: 'grocery',
        categoryId: 'meat-seafood',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-chicken-curry-cut')!.imageUrl,
        imageHint: 'chicken curry cut',
        sellerId: 'seller-1',
        subCategory: 'Chicken (Kozhi)',
        tags: ['Halaal', 'Antibiotic-free', 'Chilled Delivery'],
    },
    {
        id: 'prod-chicken-boneless',
        name: 'Chicken Breast Boneless',
        description: 'Tender, boneless chicken breast for various dishes.',
        price: 350,
        stock: 15,
        productType: 'grocery',
        categoryId: 'meat-seafood',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-chicken-boneless')!.imageUrl,
        imageHint: 'boneless chicken',
        sellerId: 'seller-1',
        subCategory: 'Chicken (Kozhi)',
        tags: ['Halaal', 'Chilled Delivery'],
    },
    {
        id: 'prod-country-chicken',
        name: 'Country Chicken (Nattu Kozhi)',
        description: 'Flavorful country chicken for traditional gravies.',
        price: 450,
        stock: 9,
        productType: 'grocery',
        categoryId: 'meat-seafood',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-country-chicken')!.imageUrl,
        imageHint: 'country chicken',
        sellerId: 'seller-1',
        subCategory: 'Chicken (Kozhi)',
        tags: ['Chilled Delivery']
    },
    {
        id: 'prod-mutton-curry-cut',
        name: 'Mutton Curry Cut',
        description: 'A mix of bone and meat pieces for rich curries.',
        price: 800,
        stock: 12,
        productType: 'grocery',
        categoryId: 'meat-seafood',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-mutton-curry-cut')!.imageUrl,
        imageHint: 'mutton curry cut',
        sellerId: 'seller-1',
        subCategory: 'Mutton & Lamb (Aattu Iraichi)',
        tags: ['Halaal', 'Chilled Delivery'],
    },
    {
        id: 'prod-mutton-keema',
        name: 'Mutton Keema',
        description: 'Finely minced mutton for various preparations.',
        price: 900,
        stock: 8,
        productType: 'grocery',
        categoryId: 'meat-seafood',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-mutton-keema')!.imageUrl,
        imageHint: 'mutton mince',
        sellerId: 'seller-1',
        subCategory: 'Mutton & Lamb (Aattu Iraichi)',
        tags: ['Chilled Delivery']
    },
    {
        id: 'prod-seer-fish',
        name: 'Seer Fish (Vanjaram)',
        description: 'Freshly caught seer fish, perfect for frying.',
        price: 950,
        stock: 7,
        productType: 'grocery',
        categoryId: 'meat-seafood',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-seer-fish')!.imageUrl,
        imageHint: 'seer fish',
        sellerId: 'seller-1',
        subCategory: 'Fresh Seafood (Meen Vagaigal)',
        tags: ['Fresh Catch', 'Chilled Delivery'],
        cleaningOptions: [
            { id: 'seer-whole', type: 'Whole' },
            { id: 'seer-slices', type: 'Slices', priceModifier: 50 },
        ],
    },
    {
        id: 'prod-prawns',
        name: 'Prawns (Iral)',
        description: 'Juicy prawns, cleaned and deveined.',
        price: 600,
        stock: 18,
        productType: 'grocery',
        categoryId: 'meat-seafood',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-prawns')!.imageUrl,
        imageHint: 'cleaned prawns',
        sellerId: 'seller-1',
        subCategory: 'Fresh Seafood (Meen Vagaigal)',
        tags: ['Fresh Catch', 'Chilled Delivery'],
        cleaningOptions: [
            { id: 'prawns-whole', type: 'Whole' },
            { id: 'prawns-cleaned', type: 'Cleaned & Gutted', priceModifier: 80 },
        ],
    },
     {
        id: 'prod-salmon',
        name: 'Atlantic Salmon Fillet',
        description: 'Premium Atlantic Salmon, rich in Omega-3.',
        price: 1200,
        stock: 10,
        productType: 'grocery',
        categoryId: 'meat-seafood',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-salmon')!.imageUrl,
        imageHint: 'salmon fillet',
        sellerId: 'seller-1',
        subCategory: 'Fresh Seafood (Meen Vagaigal)',
        tags: ['Fresh Catch', 'Chilled Delivery'],
        cleaningOptions: [
            { id: 'salmon-whole', type: 'Whole' },
            { id: 'salmon-skin-off', type: 'Skin-off', priceModifier: 100 },
        ],
    },
    {
        id: 'prod-chicken-sausages',
        name: 'Chicken Sausages',
        description: 'Ready-to-cook chicken sausages.',
        price: 250,
        stock: 30,
        productType: 'grocery',
        categoryId: 'packaged-instant-foods',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-chicken-sausages')!.imageUrl,
        imageHint: 'chicken sausages',
        sellerId: 'seller-2',
        subCategory: 'Frozen Foods',
        tags: ['Chilled Delivery']
    },
    {
        id: 'prod-chicken-nuggets',
        name: 'Chicken Nuggets',
        description: 'Crispy and delicious chicken nuggets.',
        price: 280,
        stock: 25,
        productType: 'grocery',
        categoryId: 'packaged-instant-foods',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-chicken-nuggets')!.imageUrl,
        imageHint: 'chicken nuggets',
        sellerId: 'seller-2',
        subCategory: 'Frozen Foods',
        tags: ['Chilled Delivery']
    },
    {
        id: 'prod-quail-eggs',
        name: 'Quail Eggs (Kaadai Muttai)',
        description: 'Small and nutritious quail eggs.',
        price: 80,
        stock: 50,
        productType: 'grocery',
        categoryId: 'dairy-eggs',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-quail-eggs')!.imageUrl,
        imageHint: 'quail eggs',
        sellerId: 'seller-1',
        subCategory: 'Eggs',
        tags: ['Chilled Delivery']
    },
    
    // Prepared Foods (Food Delivery)
    {
        id: 'prod-paneer-butter-masala-rte',
        name: 'Paneer Butter Masala (Heat & Eat)',
        description: 'A classic creamy tomato and paneer curry, ready in minutes.',
        price: 180,
        stock: 40,
        productType: 'food',
        categoryId: 'main-course',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-paneer-butter-masala-rte')!.imageUrl,
        imageHint: 'paneer butter masala',
        sellerId: 'seller-3',
        subCategory: 'North Indian',
        serves: '1-2 people',
        cookingMethods: ['Microwave', 'Pan Fry'],
        tags: ['No Preservatives', 'High Protein', 'Veg'],
        pairingIds: ['prod-chapati', 'prod-basmati-rice']
    },
    {
        id: 'prod-sambar-rice-rte',
        name: 'Sambar Sadam (Heat & Eat)',
        description: 'Homestyle sambar rice, just heat and serve.',
        price: 120,
        stock: 50,
        productType: 'food',
        categoryId: 'main-course',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-sambar-rice-rte')!.imageUrl,
        imageHint: 'sambar rice',
        sellerId: 'seller-3',
        subCategory: 'South Indian',
        serves: '1 person',
        cookingMethods: ['Microwave'],
        tags: ['Veg'],
    },
    {
        id: 'prod-veg-biryani-rte',
        name: 'Vegetable Biryani Tray',
        description: 'Aromatic vegetable biryani, perfect for a quick meal.',
        price: 150,
        stock: 30,
        productType: 'food',
        categoryId: 'main-course',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-veg-biryani-rte')!.imageUrl,
        imageHint: 'vegetable biryani',
        sellerId: 'seller-3',
        subCategory: 'South Indian',
        serves: '1-2 people',
        cookingMethods: ['Microwave'],
        tags: ['Veg'],
    },
    {
        id: 'prod-idli-dosa-batter',
        name: 'Idli & Dosa Batter',
        description: 'Freshly ground batter for soft idlis and crispy dosas.',
        price: 70,
        stock: 100,
        productType: 'grocery',
        categoryId: 'packaged-instant-foods',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-idli-dosa-batter')!.imageUrl,
        imageHint: 'dosa batter',
        sellerId: 'seller-3',
        subCategory: 'Ready-to-Eat Meals',
        serves: 'Family Pack',
        tags: ['No Preservatives'],
    },
    {
        id: 'prod-gulab-jamun-mix',
        name: 'Gulab Jamun Instant Mix',
        description: 'Make delicious gulab jamuns at home effortlessly.',
        price: 110,
        stock: 80,
        productType: 'grocery',
        categoryId: 'packaged-instant-foods',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-gulab-jamun-mix')!.imageUrl,
        imageHint: 'gulab jamun',
        sellerId: 'seller-3',
        subCategory: 'Instant Noodles',
    },
    {
        id: 'prod-veg-cutlet-frozen',
        name: 'Vegetable Cutlet (Frozen)',
        description: 'Crispy vegetable patties, ready to fry or bake.',
        price: 150,
        stock: 60,
        productType: 'grocery',
        categoryId: 'packaged-instant-foods',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-veg-cutlet-frozen')!.imageUrl,
        imageHint: 'vegetable cutlet',
        sellerId: 'seller-2',
        subCategory: 'Frozen Foods',
        cookingMethods: ['Deep Fry', 'Air Fryer'],
        serves: 'Approx. 10 pieces',
    },
     {
        id: 'prod-fish-fingers-frozen',
        name: 'Fish Fingers (Frozen)',
        description: 'Crispy breaded fish fingers, a perfect snack.',
        price: 220,
        stock: 40,
        productType: 'grocery',
        categoryId: 'packaged-instant-foods',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-fish-fingers')!.imageUrl,
        imageHint: 'fish fingers',
        sellerId: 'seller-2',
        subCategory: 'Frozen Foods',
        cookingMethods: ['Deep Fry', 'Air Fryer'],
    },
    {
        id: 'prod-french-fries-frozen',
        name: 'French Fries (Frozen)',
        description: 'Classic potato french fries, ready for the fryer.',
        price: 120,
        stock: 90,
        productType: 'grocery',
        categoryId: 'packaged-instant-foods',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-french-fries-frozen')!.imageUrl,
        imageHint: 'french fries',
        sellerId: 'seller-2',
        subCategory: 'Frozen Foods',
        cookingMethods: ['Deep Fry', 'Air Fryer'],
    },
    {
        id: 'prod-gobi-manchurian-rtc',
        name: 'Gobi Manchurian Mix (Ready-to-Cook)',
        description: 'Marinated cauliflower florets for perfect Gobi Manchurian.',
        price: 130,
        stock: 45,
        productType: 'food',
        categoryId: 'main-course',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-gobi-manchurian-rtc')!.imageUrl,
        imageHint: 'gobi manchurian',
        sellerId: 'seller-3',
        subCategory: 'Chinese',
        cookingMethods: ['Pan Fry'],
        serves: '2 people',
        tags: ['Veg'],
    },
    {
        id: 'prod-paneer-tikka-rtc',
        name: 'Paneer Tikka Skewers (Ready-to-Cook)',
        description: 'Marinated paneer and vegetable skewers, ready for the grill.',
        price: 220,
        stock: 35,
        productType: 'food',
        categoryId: 'main-course',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-paneer-tikka-rtc')!.imageUrl,
        imageHint: 'paneer tikka',
        sellerId: 'seller-3',
        subCategory: 'North Indian',
        cookingMethods: ['Grill', 'Pan Fry'],
        serves: '2-3 people',
        tags: ['High Protein', 'Veg'],
        pairingIds: ['prod-mint-chutney']
    },
    {
        id: 'prod-mini-tiffin-deli',
        name: 'Mini Tiffin Combo',
        description: 'A perfect breakfast combo with Idli, Vada, and Pongal.',
        price: 100,
        stock: 50,
        productType: 'food',
        categoryId: 'main-course',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-mini-tiffin-deli')!.imageUrl,
        imageHint: 'tiffin combo',
        sellerId: 'seller-3',
        subCategory: 'South Indian',
        serves: '1 person',
        tags: ['No Preservatives', 'Veg']
    },
    {
        id: 'prod-curd-rice-deli',
        name: 'Curd Rice with Pickle',
        description: 'Comforting curd rice served with a side of traditional pickle.',
        price: 80,
        stock: 60,
        productType: 'food',
        categoryId: 'main-course',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-curd-rice-deli')!.imageUrl,
        imageHint: 'curd rice',
        sellerId: 'seller-3',
        subCategory: 'South Indian',
        serves: '1 person',
        tags: ['Veg'],
    },
    {
        id: 'prod-mint-chutney',
        name: 'Mint Chutney',
        description: 'Fresh and tangy mint chutney, perfect with snacks.',
        price: 40,
        stock: 80,
        productType: 'food',
        categoryId: 'main-course',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-mint-chutney')!.imageUrl,
        imageHint: 'mint chutney',
        sellerId: 'seller-3',
        subCategory: 'Continental',
        tags: ['Veg'],
    },

    // Snacks
    {
        id: 'prod-murukku',
        name: 'Butter Murukku',
        description: 'Classic crunchy spiral snack made from rice flour and butter.',
        price: 80,
        stock: 100,
        productType: 'grocery',
        categoryId: 'snacks-beverages',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-murukku')!.imageUrl,
        imageHint: 'murukku snack',
        sellerId: 'seller-3',
        subCategory: 'Chips & Namkeen',
        variants: [
            { id: 'prod-murukku-50g', weight: '50g (Trial)', price: 20, stock: 50 },
            { id: 'prod-murukku-250g', weight: '250g', price: 80, stock: 50 },
        ],
    },
    {
        id: 'prod-thattai',
        name: 'Thattai',
        description: 'Crispy and savory flat discs, perfect with tea.',
        price: 75,
        stock: 90,
        productType: 'grocery',
        categoryId: 'snacks-beverages',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-thattai')!.imageUrl,
        imageHint: 'thattai snack',
        sellerId: 'seller-3',
        subCategory: 'Chips & Namkeen',
        pairingIds: ['prod-tea', 'prod-coffee'],
    },
    {
        id: 'prod-mixture',
        name: 'South Indian Mixture',
        description: 'A delightful mix of various fried snacks and nuts.',
        price: 120,
        stock: 80,
        productType: 'grocery',
        categoryId: 'snacks-beverages',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-mixture')!.imageUrl,
        imageHint: 'mixture snack',
        sellerId: 'seller-3',
        subCategory: 'Chips & Namkeen',
    },
    {
        id: 'prod-ribbon-pakoda',
        name: 'Ribbon Pakoda',
        description: 'Crispy ribbon-shaped snack made from gram flour.',
        price: 85,
        stock: 110,
        productType: 'grocery',
        categoryId: 'snacks-beverages',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-ribbon-pakoda')!.imageUrl,
        imageHint: 'ribbon pakoda',
        sellerId: 'seller-3',
        subCategory: 'Chips & Namkeen',
    },
    {
        id: 'prod-banana-chips',
        name: 'Nagercoil Banana Chips',
        description: 'Spicy and salty banana chips from Nagercoil.',
        price: 90,
        stock: 120,
        productType: 'grocery',
        categoryId: 'snacks-beverages',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-banana-chips')!.imageUrl,
        imageHint: 'banana chips',
        sellerId: 'seller-3',
        subCategory: 'Chips & Namkeen',
    },
    {
        id: 'prod-lays-chips',
        name: 'Lay\'s Potato Chips (Classic)',
        description: 'Classic salted potato chips.',
        price: 20,
        stock: 400,
        productType: 'grocery',
        categoryId: 'snacks-beverages',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-lays-chips')!.imageUrl,
        imageHint: 'lays chips',
        sellerId: 'seller-2',
        subCategory: 'Chips & Namkeen',
    },
    {
        id: 'prod-kadalai-mittai',
        name: 'Kovilpatti Kadalai Mittai',
        description: 'Traditional groundnut and jaggery candy from Kovilpatti.',
        price: 50,
        stock: 150,
        productType: 'grocery',
        categoryId: 'snacks-beverages',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-kadalai-mittai')!.imageUrl,
        imageHint: 'groundnut candy',
        sellerId: 'seller-3',
        subCategory: 'Chocolates',
    },
    {
        id: 'prod-adhirasam',
        name: 'Adhirasam',
        description: 'A traditional sweet pastry from Tamil cuisine.',
        price: 120,
        stock: 60,
        productType: 'grocery',
        categoryId: 'snacks-beverages',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-adhirasam')!.imageUrl,
        imageHint: 'adhirasam sweet',
        sellerId: 'seller-3',
        subCategory: 'Chocolates',
    },
    {
        id: 'prod-halwa',
        name: 'Tirunelveli Halwa',
        description: 'A rich, ghee-laden wheat halwa.',
        price: 180,
        stock: 40,
        productType: 'grocery',
        categoryId: 'snacks-beverages',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-halwa')!.imageUrl,
        imageHint: 'tirunelveli halwa',
        sellerId: 'seller-3',
        subCategory: 'Chocolates',
    },
    {
        id: 'prod-roasted-makhana',
        name: 'Roasted Makhana (Foxnuts)',
        description: 'Lightly salted and roasted foxnuts, a healthy snack.',
        price: 150,
        stock: 80,
        productType: 'grocery',
        categoryId: 'snacks-beverages',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-roasted-makhana')!.imageUrl,
        imageHint: 'roasted makhana',
        sellerId: 'seller-3',
        subCategory: 'Chips & Namkeen',
    },
    {
        id: 'prod-dry-fruit-mix',
        name: 'Dry Fruit & Nut Mix',
        description: 'A healthy mix of almonds, cashews, raisins, and walnuts.',
        price: 250,
        stock: 100,
        productType: 'grocery',
        categoryId: 'snacks-beverages',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-dry-fruits')!.imageUrl,
        imageHint: 'dry fruit mix',
        sellerId: 'seller-3',
        subCategory: 'Chips & Namkeen',
        tags: ['High Protein'],
    },


    // Beverages
    {
        id: 'prod-tea',
        name: 'Assam Black Tea',
        description: 'Strong and malty black tea.',
        price: 250,
        stock: 100,
        productType: 'grocery',
        categoryId: 'snacks-beverages',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-tea')!.imageUrl,
        imageHint: 'tea box',
        sellerId: 'seller-3',
        subCategory: 'Tea & Coffee',
        pairingIds: ['prod-marie-biscuit', 'prod-rusk', 'prod-thattai'],
    },
    {
        id: 'prod-coffee',
        name: 'Instant Filter Coffee',
        description: 'Aromatic South Indian filter coffee.',
        price: 350,
        stock: 80,
        productType: 'grocery',
        categoryId: 'snacks-beverages',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-coffee')!.imageUrl,
        imageHint: 'coffee jar',
        sellerId: 'seller-3',
        subCategory: 'Tea & Coffee',
    },
      {
        id: 'prod-bournvita',
        name: 'Bournvita Health Drink',
        description: 'Chocolate-flavored health drink for all ages.',
        price: 280,
        stock: 100,
        productType: 'grocery',
        categoryId: 'snacks-beverages',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-bournvita')!.imageUrl,
        imageHint: 'bournvita jar',
        sellerId: 'seller-3',
        subCategory: 'Tea & Coffee',
    },
    {
        id: 'prod-coke',
        name: 'Coca-Cola Can',
        description: 'Classic and refreshing Coca-Cola.',
        price: 40,
        stock: 200,
        productType: 'grocery',
        categoryId: 'snacks-beverages',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-coke')!.imageUrl,
        imageHint: 'coke can',
        sellerId: 'seller-2',
        subCategory: 'Soft Drinks',
        tags: ['Chilled Delivery']
    },
    {
        id: 'prod-coke-zero',
        name: 'Coca-Cola Zero Sugar',
        description: 'Same great taste with zero sugar.',
        price: 40,
        stock: 150,
        productType: 'grocery',
        categoryId: 'snacks-beverages',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-coke')!.imageUrl,
        imageHint: 'coke zero can',
        sellerId: 'seller-2',
        subCategory: 'Soft Drinks',
        tags: ['Chilled Delivery', 'Diet/Zero']
    },
    {
        id: 'prod-juice',
        name: 'Real Orange Juice',
        description: 'Packaged orange juice, rich in Vitamin C.',
        price: 120,
        stock: 150,
        productType: 'grocery',
        categoryId: 'snacks-beverages',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-juice')!.imageUrl,
        imageHint: 'juice carton',
        sellerId: 'seller-2',
        subCategory: 'Soft Drinks',
    },
    {
        id: 'prod-redbull',
        name: 'Red Bull Energy Drink',
        description: 'Gives you wings.',
        price: 125,
        stock: 90,
        productType: 'grocery',
        categoryId: 'snacks-beverages',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-redbull')!.imageUrl,
        imageHint: 'red bull',
        sellerId: 'seller-2',
        subCategory: 'Soft Drinks',
    },
    {
        id: 'prod-water-can',
        name: 'Packaged Drinking Water',
        description: 'Purified and safe drinking water.',
        price: 80,
        stock: 50,
        productType: 'grocery',
        categoryId: 'snacks-beverages',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-water-can')!.imageUrl,
        imageHint: 'water can',
        sellerId: 'seller-1',
        subCategory: 'Soft Drinks',
        variants: [
            { id: 'prod-water-1l', weight: '1L Bottle', price: 20, stock: 100 },
            { id: 'prod-water-20l', weight: '20L Can', price: 80, stock: 50 },
        ],
    },
    {
        id: 'prod-party-pack',
        name: 'Party Pack Combo',
        description: 'A combo of 2 Coke cans and 1 pack of mixture.',
        price: 180,
        stock: 40,
        productType: 'grocery',
        categoryId: 'snacks-beverages',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-party-pack')!.imageUrl,
        imageHint: 'party snacks drinks',
        sellerId: 'seller-2',
        subCategory: 'Chips & Namkeen',
        pairingIds: ['prod-coke', 'prod-mixture']
    },
    
    // Household Essentials
    {
        id: 'prod-floor-cleaner',
        name: 'Lizol Floor Cleaner',
        description: 'Kills 99.9% of germs, leaving a pleasant fragrance.',
        price: 190,
        stock: 80,
        productType: 'grocery',
        categoryId: 'household-essentials',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-floor-cleaner')!.imageUrl,
        imageHint: 'floor cleaner bottle',
        sellerId: 'seller-1',
        subCategory: 'Cleaning Products',
    },
    {
        id: 'prod-detergent-powder',
        name: 'Surf Excel Detergent Powder',
        description: 'Tough stain removal in just one wash.',
        price: 150,
        stock: 100,
        productType: 'grocery',
        categoryId: 'household-essentials',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-detergent-powder')!.imageUrl,
        imageHint: 'detergent powder',
        sellerId: 'seller-1',
        subCategory: 'Detergents',
    },
    {
        id: 'prod-dishwash-bar',
        name: 'Vim Dishwash Bar',
        description: 'Removes tough grease with the power of 100 lemons.',
        price: 25,
        stock: 200,
        productType: 'grocery',
        categoryId: 'household-essentials',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-dishwash-bar')!.imageUrl,
        imageHint: 'dishwash bar',
        sellerId: 'seller-1',
        subCategory: 'Dishwash Products',
    },
    {
        id: 'prod-aluminum-foil',
        name: 'Freshwrapp Aluminium Foil',
        description: 'Keeps food fresh and warm.',
        price: 120,
        stock: 150,
        productType: 'grocery',
        categoryId: 'household-essentials',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-aluminum-foil')!.imageUrl,
        imageHint: 'aluminum foil',
        sellerId: 'seller-1',
        subCategory: 'Paper Products',
    },
    {
        id: 'prod-garbage-bags',
        name: 'Garbage Bags',
        description: 'Medium size, leak-proof garbage bags.',
        price: 90,
        stock: 180,
        productType: 'grocery',
        categoryId: 'household-essentials',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-garbage-bags')!.imageUrl,
        imageHint: 'garbage bags',
        sellerId: 'seller-1',
        subCategory: 'Paper Products',
    },
    {
        id: 'prod-agarbatti',
        name: 'Mangaldeep Agarbatti',
        description: 'Long-lasting and fragrant incense sticks for pooja.',
        price: 70,
        stock: 120,
        productType: 'grocery',
        categoryId: 'household-essentials',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-agarbatti')!.imageUrl,
        imageHint: 'incense sticks',
        sellerId: 'seller-3',
        subCategory: 'Cleaning Products',
    },
    {
        id: 'prod-camphor',
        name: 'Camphor (Karpuram)',
        description: 'Pure camphor for religious ceremonies.',
        price: 50,
        stock: 150,
        productType: 'grocery',
        categoryId: 'household-essentials',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-camphor')!.imageUrl,
        imageHint: 'camphor pieces',
        sellerId: 'seller-3',
        subCategory: 'Cleaning Products',
    },
    {
        id: 'prod-mosquito-repellent',
        name: 'Good Knight Refill',
        description: 'Effective mosquito repellent for peaceful nights.',
        price: 85,
        stock: 100,
        productType: 'grocery',
        categoryId: 'household-essentials',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-mosquito-repellent')!.imageUrl,
        imageHint: 'mosquito repellent',
        sellerId: 'seller-1',
        subCategory: 'Cleaning Products',
    },

    // Personal Care & Wellness
    {
        id: 'prod-shampoo',
        name: 'Clinic Plus Shikakai Shampoo',
        description: 'Nourishing shampoo with Shikakai for naturally long and strong hair.',
        price: 180,
        stock: 100,
        productType: 'grocery',
        categoryId: 'personal-care-wellness',
        imageUrl: '/PersonalCare/himalaya purifying neem face wash.png',
        imageHint: 'shikakai shampoo bottle',
        sellerId: 'seller-1',
        subCategory: 'Hair Care',
        brand: 'Clinic Plus',
    },
    {
        id: 'prod-coconut-oil',
        name: 'Parachute Coconut Oil',
        description: '100% pure coconut oil for hair and skin.',
        price: 150,
        stock: 120,
        productType: 'grocery',
        categoryId: 'personal-care-wellness',
        imageUrl: '/PersonalCare/parachute coconut oil.png',
        imageHint: 'coconut oil bottle',
        sellerId: 'seller-1',
        subCategory: 'Hair Care',
        brand: 'Parachute',
    },
    {
        id: 'prod-soap',
        name: 'Dove Bathing Bar',
        description: 'Cream beauty bathing bar with 1/4 moisturizing cream.',
        price: 60,
        stock: 200,
        productType: 'grocery',
        categoryId: 'personal-care-wellness',
        imageUrl: '/PersonalCare/dove bathing bar.png',
        imageHint: 'soap bar',
        sellerId: 'seller-1',
        subCategory: 'Bath & Body',
        brand: 'Dove',
    },
    {
        id: 'prod-handwash',
        name: 'Dettol Handwash Refill',
        description: 'Protects from 100 illness-causing germs.',
        price: 99,
        stock: 180,
        productType: 'grocery',
        categoryId: 'personal-care-wellness',
        imageUrl: '/PersonalCare/dettol handwash refill.png',
        imageHint: 'handwash refill',
        sellerId: 'seller-1',
        subCategory: 'Bath & Body',
        brand: 'Dettol',
    },
    {
        id: 'prod-toothpaste',
        name: 'Colgate MaxFresh Toothpaste',
        description: 'Red gel toothpaste with cooling crystals for fresh breath.',
        price: 95,
        stock: 150,
        productType: 'grocery',
        categoryId: 'personal-care-wellness',
        imageUrl: '/PersonalCare/colgate maxfresh toothpaste.png',
        imageHint: 'toothpaste tube',
        sellerId: 'seller-1',
        subCategory: 'Oral Care',
        brand: 'Colgate',
    },
    {
        id: 'prod-sanitary-pads',
        name: 'Whisper Ultra Clean',
        description: 'XL+ wings for extra protection.',
        price: 180,
        stock: 100,
        productType: 'grocery',
        categoryId: 'personal-care-wellness',
        imageUrl: '/PersonalCare/whisper ultra clean.png',
        imageHint: 'sanitary pads',
        sellerId: 'seller-1',
        subCategory: 'Baby Care',
        brand: 'Whisper',
    },
    {
        id: 'prod-diapers',
        name: 'Pampers Baby Diapers',
        description: 'All-round protection with aloe vera lotion.',
        price: 550,
        stock: 80,
        productType: 'grocery',
        categoryId: 'personal-care-wellness',
        imageUrl: '/PersonalCare/pampers baby diapers.png',
        imageHint: 'baby diapers',
        sellerId: 'seller-1',
        subCategory: 'Baby Care',
        brand: 'Pampers',
    },
    {
        id: 'prod-facewash',
        name: 'Himalaya Purifying Neem Face Wash',
        description: 'Prevents pimples and purifies skin.',
        price: 140,
        stock: 110,
        productType: 'grocery',
        categoryId: 'personal-care-wellness',
        imageUrl: '/PersonalCare/himalaya purifying neem face wash.png',
        imageHint: 'facewash tube',
        sellerId: 'seller-1',
        subCategory: 'Skin Care',
        brand: 'Himalaya',
    },
    {
        id: 'prod-sunscreen',
        name: 'Neutrogena Sunscreen SPF 50+',
        description: 'Ultra Sheer Dry-Touch Sunblock.',
        price: 550,
        stock: 70,
        productType: 'grocery',
        categoryId: 'personal-care-wellness',
        imageUrl: '/PersonalCare/neutrogena sunscreen spf 50+.png',
        imageHint: 'sunscreen bottle',
        sellerId: 'seller-1',
        subCategory: 'Skin Care',
        brand: 'Neutrogena',
    },

    // E-commerce products
    {
        id: 'prod-smartphone-x',
        name: 'Smartphone Pro X',
        description: 'Latest generation smartphone with a stunning OLED display and triple camera system.',
        price: 69999,
        stock: 50,
        productType: 'ecommerce',
        categoryId: 'electronics',
        subCategory: 'Mobiles',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-smartphone')!.imageUrl,
        imageHint: 'smartphone',
        sellerId: 'seller-1',
        brand: 'Galaxy',
    },
    {
        id: 'prod-smartwatch-8',
        name: 'Smartwatch Series 8',
        description: 'Track your fitness, stay connected, and monitor your health with this advanced smartwatch.',
        price: 24999,
        stock: 75,
        productType: 'ecommerce',
        categoryId: 'electronics',
        subCategory: 'Smart Gadgets',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-smartwatch')!.imageUrl,
        imageHint: 'smartwatch',
        sellerId: 'seller-1',
        brand: 'iWatch',
    },
    {
        id: 'prod-earbuds-pro',
        name: 'Wireless Earbuds Pro',
        description: 'Immersive sound with active noise cancellation and a comfortable, secure fit.',
        price: 12999,
        stock: 120,
        productType: 'ecommerce',
        categoryId: 'electronics',
        subCategory: 'Accessories',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-earbuds')!.imageUrl,
        imageHint: 'wireless earbuds',
        sellerId: 'seller-2',
        brand: 'SoundCore',
    },
    {
        id: 'prod-charging-cable-c',
        name: 'USB-C to C Braided Cable',
        description: 'Durable and fast-charging 6ft braided cable for all your USB-C devices.',
        price: 899,
        stock: 200,
        productType: 'ecommerce',
        categoryId: 'electronics',
        subCategory: 'Accessories',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-charging-cable')!.imageUrl,
        imageHint: 'charging cable',
        sellerId: 'seller-2',
        brand: 'CableMax',
    },
    {
        id: 'prod-power-bank-10k',
        name: '10000mAh Slim Power Bank',
        description: 'Charge your devices on the go with this slim and powerful power bank.',
        price: 1999,
        stock: 90,
        productType: 'ecommerce',
        categoryId: 'electronics',
        subCategory: 'Accessories',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-power-bank')!.imageUrl,
        imageHint: 'power bank',
        sellerId: 'seller-1',
        brand: 'ChargeUp',
    },
    {
        id: 'prod-smart-speaker-mini',
        name: 'Smart Home Speaker Mini',
        description: 'Your voice-controlled assistant for music, news, and smart home control.',
        price: 3499,
        stock: 60,
        productType: 'ecommerce',
        categoryId: 'electronics',
        subCategory: 'Smart Gadgets',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-smart-speaker')!.imageUrl,
        imageHint: 'smart speaker',
        sellerId: 'seller-2',
        brand: 'Echo',
    },
    {
        id: 'prod-men-tshirt',
        name: 'Men\'s Graphic T-Shirt',
        description: 'Comfortable cotton t-shirt with a stylish graphic print.',
        price: 799,
        stock: 150,
        productType: 'ecommerce',
        categoryId: 'fashion',
        subCategory: 'Men\'s Clothing',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-men-tshirt')!.imageUrl,
        imageHint: 'men t-shirt',
        sellerId: 'seller-3',
        brand: 'StyleUp',
    },
    {
        id: 'prod-men-jeans',
        name: 'Men\'s Slim Fit Jeans',
        description: 'Classic blue slim fit jeans for a modern look.',
        price: 2499,
        stock: 80,
        productType: 'ecommerce',
        categoryId: 'fashion',
        subCategory: 'Men\'s Clothing',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-men-jeans')!.imageUrl,
        imageHint: 'men jeans',
        sellerId: 'seller-3',
        brand: 'DenimCo',
    },
    {
        id: 'prod-women-dress',
        name: 'Floral Summer Dress',
        description: 'A light and airy floral dress, perfect for summer.',
        price: 1999,
        stock: 100,
        productType: 'ecommerce',
        categoryId: 'fashion',
        subCategory: 'Women\'s Clothing',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-women-dress')!.imageUrl,
        imageHint: 'summer dress',
        sellerId: 'seller-3',
        brand: 'Bella',
    },
    {
        id: 'prod-women-saree',
        name: 'Silk Blend Saree',
        description: 'An elegant silk blend saree for special occasions.',
        price: 4999,
        stock: 60,
        productType: 'ecommerce',
        categoryId: 'fashion',
        subCategory: 'Women\'s Clothing',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-women-saree')!.imageUrl,
        imageHint: 'silk saree',
        sellerId: 'seller-3',
        brand: 'EthnicWeaves',
    },
    {
        id: 'prod-kids-tshirt',
        name: 'Kids Dino Graphic T-Shirt',
        description: 'A fun and colorful dinosaur-themed t-shirt for kids.',
        price: 499,
        stock: 200,
        productType: 'ecommerce',
        categoryId: 'fashion',
        subCategory: 'Kids Wear',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-kids-tshirt')!.imageUrl,
        imageHint: 'kids t-shirt',
        sellerId: 'seller-3',
        brand: 'TinyTots',
    },
    {
        id: 'prod-sneakers',
        name: 'Classic Canvas Sneakers',
        description: 'Timeless canvas sneakers for everyday wear.',
        price: 2999,
        stock: 120,
        productType: 'ecommerce',
        categoryId: 'footwear',
        subCategory: 'Casual Shoes',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-sneakers')!.imageUrl,
        imageHint: 'casual sneakers',
        sellerId: 'seller-2',
        brand: 'WalkEasy',
    },
    {
        id: 'prod-running-shoes',
        name: 'Pro-Run Athletic Shoes',
        description: 'Lightweight and breathable running shoes for peak performance.',
        price: 4999,
        stock: 80,
        productType: 'ecommerce',
        categoryId: 'footwear',
        subCategory: 'Sports Shoes',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-running-shoes')!.imageUrl,
        imageHint: 'running shoes',
        sellerId: 'seller-1',
        brand: 'QuickPace',
    },
    {
        id: 'prod-sandals',
        name: 'Leather Comfort Sandals',
        description: 'Comfortable and stylish leather sandals for warm weather.',
        price: 1499,
        stock: 150,
        productType: 'ecommerce',
        categoryId: 'footwear',
        subCategory: 'Sandals',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-sandals')!.imageUrl,
        imageHint: 'leather sandals',
        sellerId: 'seller-3',
        brand: 'SunStrider',
    },
    {
        id: 'prod-backpack',
        name: 'Modern Laptop Backpack',
        description: 'A sleek and durable backpack with a padded laptop compartment.',
        price: 3999,
        stock: 110,
        productType: 'ecommerce',
        categoryId: 'accessories',
        subCategory: 'Bags',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-backpack')!.imageUrl,
        imageHint: 'laptop backpack',
        sellerId: 'seller-2',
        brand: 'UrbanPack',
    },
    {
        id: 'prod-analog-watch',
        name: 'Classic Analog Watch',
        description: 'An elegant timepiece with a leather strap and stainless steel case.',
        price: 8999,
        stock: 70,
        productType: 'ecommerce',
        categoryId: 'accessories',
        subCategory: 'Watches',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-watch')!.imageUrl,
        imageHint: 'analog watch',
        sellerId: 'seller-1',
        brand: 'Timeless',
    },
    {
        id: 'prod-sunglasses',
        name: 'Aviator Sunglasses',
        description: 'Iconic aviator sunglasses with UV protection.',
        price: 2599,
        stock: 180,
        productType: 'ecommerce',
        categoryId: 'accessories',
        subCategory: 'Sunglasses',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-sunglasses')!.imageUrl,
        imageHint: 'aviator sunglasses',
        sellerId: 'seller-3',
        brand: 'SunShade',
    },
    {
        id: 'prod-non-stick-pan',
        name: 'Non-Stick Frying Pan',
        description: 'A durable non-stick pan for healthy, everyday cooking.',
        price: 1499,
        stock: 100,
        productType: 'ecommerce',
        categoryId: 'home-kitchen',
        subCategory: 'Cookware',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-non-stick-pan')!.imageUrl,
        imageHint: 'frying pan',
        sellerId: 'seller-2',
        brand: 'KitchenPro',
    },
    {
        id: 'prod-pressure-cooker',
        name: 'Steel Pressure Cooker (5L)',
        description: 'A high-quality stainless steel pressure cooker for fast and efficient cooking.',
        price: 2999,
        stock: 70,
        productType: 'ecommerce',
        categoryId: 'home-kitchen',
        subCategory: 'Cookware',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-pressure-cooker')!.imageUrl,
        imageHint: 'pressure cooker',
        sellerId: 'seller-1',
        brand: 'Prestige',
    },
    {
        id: 'prod-food-containers',
        name: 'Glass Food Container Set',
        description: 'A set of 3 microwave-safe glass containers for storing food.',
        price: 999,
        stock: 120,
        productType: 'ecommerce',
        categoryId: 'home-kitchen',
        subCategory: 'Storage Items',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-food-containers')!.imageUrl,
        imageHint: 'food containers',
        sellerId: 'seller-2',
        brand: 'StoreFresh',
    },
    {
        id: 'prod-spice-rack',
        name: 'Revolving Spice Rack',
        description: 'A stylish 16-jar revolving spice rack for your kitchen counter.',
        price: 1299,
        stock: 90,
        productType: 'ecommerce',
        categoryId: 'home-kitchen',
        subCategory: 'Storage Items',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-spice-rack')!.imageUrl,
        imageHint: 'spice rack',
        sellerId: 'seller-3',
        brand: 'SpiceOrganize',
    },
    {
        id: 'prod-decorative-vase',
        name: 'Ceramic Decorative Vase',
        description: 'An elegant ceramic vase to brighten up your living space.',
        price: 1799,
        stock: 60,
        productType: 'ecommerce',
        categoryId: 'home-kitchen',
        subCategory: 'Home Decor',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-decorative-vase')!.imageUrl,
        imageHint: 'decorative vase',
        sellerId: 'seller-3',
        brand: 'DecorArt',
    },
    {
        id: 'prod-wall-art',
        name: 'Abstract Canvas Wall Art',
        description: 'A modern abstract painting to add a touch of sophistication to your walls.',
        price: 3499,
        stock: 50,
        productType: 'ecommerce',
        categoryId: 'home-kitchen',
        subCategory: 'Home Decor',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-wall-art')!.imageUrl,
        imageHint: 'wall art',
        sellerId: 'seller-3',
        brand: 'CanvasCreations',
    },
    {
        id: 'prod-lipstick',
        name: 'Matte Red Lipstick',
        description: 'A vibrant, long-lasting matte red lipstick.',
        price: 1299,
        stock: 150,
        productType: 'ecommerce',
        categoryId: 'beauty-personal-care',
        subCategory: 'Makeup',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-lipstick')!.imageUrl,
        imageHint: 'red lipstick',
        sellerId: 'seller-2',
        brand: 'Glamour',
    },
    {
        id: 'prod-moisturizer',
        name: 'Hydrating Face Moisturizer',
        description: 'A lightweight, daily moisturizer for all skin types.',
        price: 2499,
        stock: 100,
        productType: 'ecommerce',
        categoryId: 'beauty-personal-care',
        subCategory: 'Skin Care',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-moisturizer')!.imageUrl,
        imageHint: 'face moisturizer',
        sellerId: 'seller-1',
        brand: 'Glow',
    },
    {
        id: 'prod-hair-dryer',
        name: 'Professional Hair Dryer',
        description: 'A powerful 2000W hair dryer for fast, salon-quality results.',
        price: 3999,
        stock: 80,
        productType: 'ecommerce',
        categoryId: 'beauty-personal-care',
        subCategory: 'Hair Styling Tools',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-hair-dryer')!.imageUrl,
        imageHint: 'hair dryer',
        sellerId: 'seller-2',
        brand: 'StylePro',
    },
    {
        id: 'prod-building-blocks',
        name: 'Colorful Building Blocks',
        description: 'A 100-piece set of wooden building blocks to inspire creativity.',
        price: 1499,
        stock: 100,
        productType: 'ecommerce',
        categoryId: 'baby-kids',
        subCategory: 'Toys',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-building-blocks')!.imageUrl,
        imageHint: 'building blocks',
        sellerId: 'seller-3',
        brand: 'CreativeKidz',
    },
    {
        id: 'prod-teddy-bear',
        name: 'Plush Teddy Bear',
        description: 'A soft and cuddly 12-inch teddy bear, perfect for all ages.',
        price: 999,
        stock: 150,
        productType: 'ecommerce',
        categoryId: 'baby-kids',
        subCategory: 'Toys',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-teddy-bear')!.imageUrl,
        imageHint: 'teddy bear',
        sellerId: 'seller-3',
        brand: 'CuddleCo',
    },
    {
        id: 'prod-baby-lotion',
        name: 'Gentle Baby Lotion',
        description: 'Hypoallergenic and pediatrician-tested baby lotion for sensitive skin.',
        price: 499,
        stock: 200,
        productType: 'ecommerce',
        categoryId: 'baby-kids',
        subCategory: 'Baby Essentials',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-baby-lotion')!.imageUrl,
        imageHint: 'baby lotion',
        sellerId: 'seller-1',
        brand: 'BabySoft',
    },
    {
        id: 'prod-baby-wipes',
        name: 'Sensitive Baby Wipes (80 count)',
        description: 'Fragrance-free and gentle baby wipes for easy cleanups.',
        price: 299,
        stock: 250,
        productType: 'ecommerce',
        categoryId: 'baby-kids',
        subCategory: 'Baby Essentials',
        imageUrl: PlaceHolderImages.find(p => p.id === 'prod-baby-wipes')!.imageUrl,
        imageHint: 'baby wipes',
        sellerId: 'seller-1',
        brand: 'BabySoft',
    },
];

const users: User[] = [
  { id: 'user-1', name: 'Alice', email: 'alice@example.com', role: 'Customer' },
  { id: 'admin-1', name: 'Admin User', email: 'admin@example.com', role: 'Admin' },
  { id: 'delivery-1', name: 'Bob', email: 'bob@example.com', role: 'Delivery' },
  { id: 'seller-1', name: 'FarmFresh Organics', email: 'contact@farmfresh.com', role: 'Seller' },
  { id: 'seller-2', name: 'Artisan Bakery', email: 'hello@artisanbakery.com', role: 'Seller' },
  { id: 'seller-3', name: 'Amma\'s Kitchen', email: 'support@ammaskitchen.com', role: 'Seller' },
];

const reviews: Review[] = [
  { id: 'rev-1', productId: 'prod-apple', userId: 'user-1', rating: 5, comment: 'These apples are incredibly fresh and crisp!', timestamp: '2023-10-26T10:00:00Z' },
  { id: 'rev-2', productId: 'prod-apple', userId: 'user-2', rating: 4, comment: 'Good quality, but a bit pricey.', timestamp: '2023-10-25T14:30:00Z' },
  { id: 'rev-3', productId: 'prod-idli-dosa-batter', userId: 'user-1', rating: 5, comment: 'Tasted just like homemade. Excellent!', timestamp: '2023-10-24T18:00:00Z' },
  { id: 'rev-4', productId: 'prod-milk-pouch', userId: 'user-1', rating: 5, comment: 'Aavin milk is always reliable.', timestamp: '2024-07-15T08:00:00Z' },
  { id: 'rev-5', productId: 'prod-chicken-curry-cut', userId: 'user-1', rating: 4, comment: 'Chicken was fresh but pieces were a bit small.', timestamp: '2024-07-14T19:30:00Z' },
  { id: 'rev-6', productId: 'prod-smartphone-x', userId: 'user-1', rating: 5, comment: 'Amazing phone! The camera is top-notch.', timestamp: '2024-07-20T12:00:00Z'},
  { id: 'rev-7', productId: 'prod-smartwatch-8', userId: 'user-1', rating: 4, comment: 'Great watch, but battery could be better.', timestamp: '2024-07-21T15:00:00Z'},
  { id: 'rev-8', productId: 'prod-men-tshirt', userId: 'user-1', rating: 5, comment: 'Great fit and very comfortable material.', timestamp: '2024-07-22T10:00:00Z'},

];

const orders: Order[] = [
    {
        id: 'order-1',
        userId: 'user-1',
        items: [
            { productId: 'prod-apple', quantity: 2, price: 150 },
            { productId: 'prod-milk-pouch', quantity: 1, price: 22 }
        ],
        totalAmount: 322,
        status: 'Delivered',
        deliveryAddress: {
            name: 'Alice',
            address: '123 Green St',
            city: 'Chennai',
            zip: '600001'
        },
        timestamp: '2024-07-15T10:00:00Z'
    },
    {
        id: 'order-2',
        userId: 'admin-1', // Assuming admin can also be a customer
        items: [
            { productId: 'prod-idli-dosa-batter', quantity: 2, price: 70 },
            { productId: 'prod-coke', quantity: 4, price: 40 }
        ],
        totalAmount: 300,
        status: 'Confirmed',
        deliveryAddress: {
            name: 'Admin User',
            address: '456 Park Ave',
            city: 'Chennai',
            zip: '600008'
        },
        timestamp: '2024-07-20T11:30:00Z'
    },
     {
        id: 'order-3',
        userId: 'user-1',
        items: [
            { productId: 'prod-mutton-curry-cut', quantity: 1, price: 800 },
            { productId: 'prod-basmati-rice', quantity: 1, price: 180, variantId: 'prod-basmati-rice-1kg' },
        ],
        totalAmount: 980,
        status: 'Out for Delivery',
        deliveryAddress: {
            name: 'Alice',
            address: '123 Green St',
            city: 'Chennai',
            zip: '600001'
        },
        timestamp: '2024-07-21T09:00:00Z'
    }
];

export const getCategories = () => categories;
export const getProducts = () => products;
export const getFeaturedProducts = () => {
    const grocery = products.find(p => p.id === 'prod-apple');
    const food = products.find(p => p.id === 'prod-paneer-butter-masala-rte');
    const ecommerce = products.find(p => p.id === 'prod-men-tshirt');
    const ecommerce2 = products.find(p => p.id === 'prod-smartphone-x');
    return [grocery, food, ecommerce, ecommerce2, products[3], products[4], products[5], products[7]].filter(Boolean) as Product[];
};
export const getProductById = (id: string) => products.find(p => p.id === id);
export const getProductsByCategory = (categoryId: string) => products.filter(p => p.categoryId === categoryId);
export const getProductsBySeller = (sellerId: string) => products.filter(p => p.sellerId === sellerId);

export const getUsers = () => users;
export const getUserById = (id: string) => users.find(u => u.id === id);

export const getReviews = () => reviews;
export const getReviewsForProduct = (productId: string) => reviews.filter(r => r.productId === productId);

export const getOrders = () => orders;
export const getOrderById = (id: string) => orders.find(o => o.id === o.id);
export const getOrdersByUser = (userId: string) => orders.filter(o => o.userId === userId);
